### ISSUE TITLE
lumpy_filter seeks for libcrypto on the system lib PATH insted of LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by aksenia** [brentp/smoove#102]
Hi, 
I am struggling to get smoove to run (openSUSE 15.0, install with all dependencies via conda in a separate env);
The error is on the lumpy_filter step:

[smoove]:([E]lumpy-filter) 2020/01/29 12:06:09 lumpy_filter: /usr/lib64/libcrypto.so.1.0.0: version `OPENSSL_1_1_1' not found (required by /home/myuser/anaconda3/envs/sv/bin/../lib/./libssl.so.1.1)

The needed libcrypto is in the conda lib, but lumpy insists on looking into the system PATh even though I explicitly set LD_LIBRARY_PATH to point to conda lib. How can I fix this? 
Thanks in advance!

**Comment by aksenia** [comment]
Hi again, 

I was able to solve this linking problem by wiping an environment and installing lumpy-sv from conda first and then smoove. The linking issue was withing the lumpy dependency in the smoove package. The software seems to be running now. Please feel free to close the issue. I leave it open so you could have a look first.

**Comment by brentp** [comment]
ok. glad you figured it out.
