### ISSUE TITLE
QUAL score scaling

### ISSUE THREAD

**Issue by aderzelle** [brentp/smoove#107]
Hello,

How is exactly the QUAL score scaled? In my cohort vcf I get 

```
summary(DT$QUAL)
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
     0.0    840.9   3353.7   5101.1   8436.3 234784.0 
```

Is this expected, that the range of values is so wide? 

thank you

**Comment by brentp** [comment]
that calculated in lumpy and/or svtyper, so you'd have to ask there about the details, but IMO, it seems reasonable that it's that wide.
