### ISSUE TITLE
Filtering output SVs

### ISSUE THREAD

**Issue by iwilson-liv** [brentp/smoove#109]
I have entered 12 samples (each derived from pooled tissue from clonal populations) into Smoove and, following filtering using bcftools, have successfully output a VCF file of HQ variants.

`smoove call --name BMH_clones_CNVs --exclude BMH21_Round3.repeats_only.bed --fasta BMH21_Flye_60x_assembly.fasta -p 1 --genotype Coverage_Depth/*.bam --outdir Coverage_Depth/ --duphold;`

`bcftools view -i '(SVTYPE = "DEL" & FMT/DHFFC[0] < 0.7) | (SVTYPE = "DUP" & FMT/DHBFC[0] > 1.3)' BMH_clones_CNVs-smoove.genotyped.vcf.gz > BMH_clones_CNVs-smoove.genotyped.HQ.vcf;`

Do you have any recommendations as to how to further filter out any calls with dubious genotypes, please? From what I can tell, filtering by QUAL or average SQ may help, but I am wary, for example, of calls consisting only of heterozygous calls, and wondered what methods you suggest for dealing with such uncertain calls?

**Comment by brentp** [comment]
just to clarify, the bcftools command will only get variants for the first sample (the `[0]`th sample).
to get other types of variants and across samples, you can use [slivar](https://github.com/brentp/slivar).

I haven't found QUAL or SQ to work well for smoove output. If you can filter on duphold output, that does quite well. Do you have families? or are these unrelated samples?

@fakedrtom has a set of filters that he uses. Maybe he can share them here.

**Comment by iwilson-liv** [comment]
Thanks for the quick reply @brentp  and for clarifying what the bcftools command does - I should have spotted that! I'll use slivar as you recommended and see what the 'HQ' variants are after filtering across all samples, but I'd definitely be interested to see @fakedrtom's filters too if possible, in case there's something else I'm missing.

The samples are all clones of the same species taken from the same population but, lacking any kind of pedigree info, they're ostensibly unrelated.

**Comment by brentp** [comment]
ok. so you can use `--sample-expr` in `slivar`.
Here's what I have used:
```
slivar expr \
  --info "variant.call_rate > 0.5 && ((INFO.SVTYPE == 'DEL') ||
(INFO.SVTYPE == 'DUP'))" \
  --sample-expr \
    "LQHET:sample.alts == 1 && (((sample.DHFFC > 0.75) && (INFO.SVTYPE
== 'DEL')) || ((sample.DHFFC < 1.25) && INFO.SVTYPE == 'DUP'))" \
  --sample-expr \
    "HQHET:sample.alts == 1 && (((sample.DHFFC < 0.75) && (INFO.SVTYPE
== 'DEL')) || ((sample.DHFFC > 1.25) && INFO.SVTYPE == 'DUP'))" \
  --sample-expr \
    "HQHA:sample.alts == 2 && (((sample.DHFFC < 0.5) && (INFO.SVTYPE
== 'DEL')) || ((sample.DHFFC > 1.5) && INFO.SVTYPE == 'DUP'))" \
  -o $out \
  -p $ped \
  --vcf $vcf
```

**Comment by fakedrtom** [comment]
My filters are quite similar to those that @brentp just posted using slivar. The duphold filters (DHFFC) are the most vital filters that I use. If possible, I would also recommend filtering based on population allele frequencies. Such metrics exist for humans, but if you are dealing with another species this might not be available for you.

**Comment by iwilson-liv** [comment]
Many thanks both, I really appreciate the help.  That's good to know that the duphold filters are the main filters though. Presumably I can just write a quick one-liner to parse the Slivar output to remove any variant sites with 'LQHET' genotypes or, say, variants that I decide have too many heterozygous genotypes to be trusted?

@fakedrtom - unfortunately, yes, population allele frequencies are out of the question in this case. Would that I could!

@brentp, those commands worked first time, thanks. Somewhat confusingly though, I found that the following 2 versions of the command output different numbers of variant sites (the first command passes 15 more lines). I thought only the 'info' section of the command actually filtered anything at this stage, so do you have any idea why there's a difference in output numbers?

`~/Applications/slivar.dms expr --info "variant.call_rate > 0.5 && ((INFO.SVTYPE == 'DEL') || (INFO.SVTYPE == 'DUP'))" --pass-only -o BMH_clones_CNVs-smoove.genotyped.HQ_redo.vcf --vcf BMH_clones_CNVs-smoove.genotyped.vcf`

`~/Applications/slivar.dms expr --info "variant.call_rate > 0.5 && ((INFO.SVTYPE == 'DEL') || (INFO.SVTYPE == 'DUP'))" --sample-expr "LQHET:sample.alts == 1 && (((sample.DHFFC > 0.75) && (INFO.SVTYPE == 'DEL')) || ((sample.DHFFC < 1.25) && INFO.SVTYPE == 'DUP'))" --sample-expr "HQHET:sample.alts == 1 && (((sample.DHFFC < 0.75) && (INFO.SVTYPE == 'DEL')) || ((sample.DHFFC > 1.25) && INFO.SVTYPE == 'DUP'))" --sample-expr "HQHA:sample.alts == 2 && (((sample.DHFFC < 0.5) && (INFO.SVTYPE == 'DEL')) || ((sample.DHFFC > 1.5) && INFO.SVTYPE == 'DUP'))" --pass-only -o BMH_clones_CNVs-smoove.genotyped.HQ_redo.vcf --vcf BMH_clones_CNVs-smoove.genotyped.vcf`

**Comment by brentp** [comment]
when --info and --sample-expr (and --pass-only) are used, then the output requires that --info and at least one --sample-expr passes. with only --info, that's all that is required to pass, so we expect more variants for your first command.
