### ISSUE TITLE
panic: bam reagroup: more than one RG for

### ISSUE THREAD

**Issue by jonathan-velotta** [brentp/smoove#114]
Hello,

Is this error because I have merged samples into a single bam? If I'm trying to run smoove on a pool of samples, would you recommend re-mapping of all individuals from a population at once?

Thanks,
Jon

**Comment by jonathan-velotta** [comment]
Here is the code I used:
docker1 run -it brentp/smoove sh -c 'smoove call -x -d --outdir /workdir/results-pool/ --exclude /workdir/Mmenidia_refgenome_anchored.all_renamed_v2.mask.complex_repeats.bed --name pool --fasta /workdir/Mmenidia_refgenome_anchored.all_renamed_v2.fasta -p 10 --genotype /workdir/pools/*pool.bam'

pool.bam files are ~50 merged BAMs from each population of ~12 populations

**Comment by brentp** [comment]
In order to use smoove, you'll need to split out your bams so that there is a single sample per bam

**Comment by jonathan-velotta** [comment]
Can smoove work on pools of individuals? Can I concatenate individuals and then map? I am wondering how best to get smoove to run on a pool of samples, because it is difficult to assign SVs with low coverage data.

**Comment by brentp** [comment]
I don't think it would work well on pooled data. But, in order for it to work at all, it must be run on a BAM that contains only a single sample.

**Comment by jonathan-velotta** [comment]
Thank you, Brent
