### ISSUE TITLE
Many more DUPS than DELS across most samples

### ISSUE THREAD

**Issue by andrewSharo** [brentp/smoove#117]
Hi Brent,

Thank you for making smoove, it's a great method! I am using an older version (v0.1.7) to compare with 10X's longranger caller (which came out around the same time as v0.1.7). So far smoove performs very well in comparison. I am however finding that smoove calls a drastically larger number of duplications and inversions compared to deletions. This seems to still hold, even when retaining only MSHQ=4 variants. For example, in one vcf there were 27,196 DUP, 27,311 INV, and 2,840 DEL (this only considers MSHQ=4 variants) and this is typical of the samples I have run. I am wondering if this is just a feature of duplications and inversions being more difficult to call with confidence and if you have noticed this previously. I do think think the majority of these duplications are spurious, although they often have high quality (>100 GQ/SQ). v0.1.7 was before you included duphold, so I haven't been able to use that to filter further. This analysis is being done on 150 bp paired end linked-reads (10x Genomics) at about 60x depth with the barcode trimmed off the forward read. Just want to get your perspective on how unusual this ratio of DUPS to DELS is.

Best, Andrew

**Comment by brentp** [comment]
Hi Andrew, you'll have to filter on DHFFC (from duphold) to get any kind of precision from smoove. The MSHQ was my best attempt, but seeing how poorly it worked is part of what motivated duphold. Is there something keeping you from updating?
