### ISSUE TITLE
smoove paste error

### ISSUE THREAD

**Issue by BioInf2305** [brentp/smoove#120]
I am running smoove pipeline for SV calling in multiple samples. Note that these samples have different insert sizes, i.e. some samples have 2 x 100 bp Illumina paired-end sequencing data , while some have 2 x 150 bp Illumina paired-end sequencing data. I successfully installed the dependencies and run the first two steps of smoove pipeline. However, in the third step (smoove paste) it generated the following message: "please make sure that all files have the same number of variants"

![Screenshot from 2020-08-04 16-01-21](https://user-images.githubusercontent.com/58446112/89303902-188e9c00-d66d-11ea-9342-3392b245eacc.png)

does this message mean that something went wrong in the previous two steps? And does this difference in insert sizes between the samples produce correct SV genotypes?

**Comment by brentp** [comment]
at this stage in the pipeline, all files *must* have the same number of variants. You may have to start again with the call step. You could retry the call step with the single sample that has a disparate number. 
Also ensure that you ran smoove call with the same parameters for every sample.

**Comment by BioInf2305** [comment]
Thanks, I did what you suggested and this time the "paste" step worked properly. I have another query for which I will open a new issue, hope it is alright.
