### ISSUE TITLE
seeking a clarification concerning smoove genotype steps 

### ISSUE THREAD

**Issue by BioInf2305** [brentp/smoove#121]
First of all thank you very much for this Structural variation (SV) calling tool which is really smooth. 

I have a question concerning a third step, "smoove genotype". In this step, smoove genotypes all the samples at all the sites (present in the merged vcf file, generated using "merge" step) present in the "merged" vcf file. However, after this step, I get SV genotypes (which is not homozygous reference) for sites which were not identified as encompassing SVs in particular samples after the first step--"smoove call". Let me elaborate this in details: 

for instance, "smoove call" identified a heterozygous deletion encompassing these genomic co-ordinates: 1: 136,215-137,161 in Sample A but not in Sample B. Now after "smoove merge" and "smoove genotype", the genotype for sample B at the above mentioned co-ordinates is also heterozygous deletion. Now my question is, how is it possible? coz there was no SV called at these positions in sample B in the first step itself, but now this sample has SV genotypes after "smoove genotype" step?  I would really appreciate it if you clarify this. Thank you in advance.

**Comment by brentp** [comment]
The bounds of the structural variant and the confidence intervals (CIPOS, CIEND) change with merge, so in some samples, more reads may be collected and then get classified as heterozygous.
