### ISSUE TITLE
how to solve: "couldn't find sample from bam: or ENV in vcf which had SRRxxxxxx"

### ISSUE THREAD

**Issue by Zhao-Zhangyi** [brentp/smoove#122]
the error came when I ran duphold in the smoove environment, but the bam and vcf were correct

**Comment by brentp** [comment]
this means the sample name in your bam/cram read-group does match the sample name in the VCF.
does your bam/cram have a read-group?

**Comment by Zhao-Zhangyi** [comment]
no it doesn't (output nothing when grep '@RG')

**Comment by Zhao-Zhangyi** [comment]
no it doesn't (output nothing when `grep '@RG'`)

**Comment by brentp** [comment]
ok. you'll have to run smoove with a bam file that contains read group(s).
