### ISSUE TITLE
"out of memory" when running small cohorts

### ISSUE THREAD

**Issue by pauline-ng** [brentp/smoove#123]
Hi Brent,

Thanks for writing smoov, it has made my life a lot "smoover"!

I can successfully run 5 .bam files using the small-cohort command, but when I try 6, I get an out of memory error. 

The error is below:

`docker run -it -v /data:/data brentp/smoove smoove call -x --name smoov_cohort --exclude /data/SV/ceph18.b37.lumpy.exclude.2014-01-15.bed --fasta  /data/SV/ref_fasta/hs37d5.fa.gz -p 12 --genotype /data/SV/bam/*.bam  --outdir /data/SV/

[smoove] 2020/08/14 23:28:43 starting with version 0.2.5
[smoove] 2020/08/14 23:28:43 calculating bam stats for 6 bams
[smoove] 2020/08/14 23:29:07 done calculating bam stats
out of memorypanic: exit status 1

goroutine 112142 [running]:
github.com/brentp/smoove/lumpy.check(...)
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:54
github.com/brentp/smoove/lumpy.remove_sketchy(0xc0000ee9a0, 0x1a, 0x3e8, 0x7fffd6059d88, 0x1f, 0x7fffd6059d4f, 0x30, 0xc0000bdb80, 0x4, 0x4, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/depthfilter.go:232 +0x1818
github.com/brentp/smoove/lumpy.remove_sketchy_all.func1(0xc0000b8a20, 0x3e8, 0x7fffd6059d88, 0x1f, 0x7fffd6059d4f, 0x30, 0xc0000bdb80, 0x4, 0x4, 0x1, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/depthfilter.go:399 +0x231
created by github.com/brentp/smoove/lumpy.remove_sketchy_all
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/depthfilter.go:397 +0x191
`

Any hints on how to get it to run with a larger number of samples? (The README page said up to 40 can be run). 

Thank you,
Pauline

**Comment by brentp** [comment]
how much memory is on the machine you're using?

you could also try with a decompressed and index fasta. i am surpised that a fasta.gz even works.

**Comment by pauline-ng** [comment]
Dear Brent,

Thank you, changing the "--fasta" to a decompressed fasta worked!

Best,
Pauline
