### ISSUE TITLE
The meaning of the parameters

### ISSUE THREAD

**Issue by tyyiyi** [brentp/smoove#126]
Hello, smoove is really a great software. It helps me detect structural variation in the data. I have some doubts about its output. I hope you can explain it to me:
Look at a record:
#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT 256T_S8_L002 256N_S7_L002
chr3 41224322 324 N <DEL> 63802.1. SVTYPE=DEL;SVLEN=-607;END=41224929;STRANDS=+-:1875;CIPOS=0,0;CIEND=0,0;CIPOS95=0,0;CIEND95=0 ,0;SU=1875;PE=799;SR=1076;PRPOS=1;PREND=1;AC=1;AN=4 GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS: AS:ASC:RP:AP:AB 0/1:200:63802.1:-6528,-148,-3091:8245:5290:2954:5289:2953:2924:1079:328:2365:1546:0.36 0/0 :200:0:-2,-3029,-10093:10113:10108:5:10107:4:5538:1:0:4569:2:0.0004

problem:
1. Shouldn't DP be the sum of AO and RO? Why is AO+RO always 1 smaller than DP?
2. What exactly does QR, QA, RS, AS, ASC, RP, AP mean? Can you explain it based on the record above?
3. How should I calculate the ALT allele frequency of the tumor?  if I want to get a variation with the frequency greater than 0.2 in the tumor and less than 0.01 in the paired normal sample, What should I do?

Thanks a lot
Tang

**Comment by tyyiyi** [comment]
When doing a smoove call, he will generate disc.bam. I want to know, how does he judge a pair of reads as discordant reads? What is the predefined distance? Why?
My script:
$smoove call --outdir $out --name ${tumor}_${normal} --exclude $bed --fasta $ref -p 1 --genotype $tdata/$tumor.MarkDuplicates.bam $ndata/$normal.MarkDuplicates.bam

**Comment by tyyiyi** [comment]
When doing a smoove call, he will generate disc.bam. I want to know, how does he judge a pair of reads as discordant reads? What is the predefined distance?
My script:
$smoove call --outdir $out --name ${tumor}_${normal} --exclude $bed --fasta $ref -p 1 --genotype $tdata/$tumor.MarkDuplicates.bam $ndata/$normal.MarkDuplicates.bam

**Comment by brentp** [comment]
> * Shouldn't DP be the sum of AO and RO? Why is AO+RO always 1 smaller than DP?
> * What exactly does QR, QA, RS, AS, ASC, RP, AP mean? Can you explain it based on the record above?
> * How should I calculate the ALT allele frequency of the tumor?  if I want to get a variation with the frequency greater than 0.2 in the tumor and less than 0.01 in the paired normal sample, What should I do?

These are all questions that apply to svtyper. smoove uses svtyper, but it (and lumpy) is responsible for calling.
For frequency > 0.2 in tumor and < 0.1 in normal you can use expressions in [slivar](https://github.com/brentp/slivar) or bcftools

**Comment by brentp** [comment]
> What is the predefined distance?

This is determined by bwa (or your aligner). It samples reads and determines the distribution. It uses a SAM flag to indicate which are discordant.
