### ISSUE TITLE
panic: open sample.bam: no such file or directory

### ISSUE THREAD

**Issue by faramarzgsm** [brentp/smoove#127]
Hello dear
When I run smoove by docker, process terminated by this error: "panic: open NGS/row/bbbb.bam: no such file or directory".
I'm new user of linux operating system, and will be happy if you help me to solve this issue.
My command is:

> sudo docker run -it brentp/smoove smoove call --name dddd --fasta NGS/gr/GRef-BWA/gr.fa --exclude NGS/soft/smoove/exclude.bed --processes 1 --outdir NGS/result-smoove --genotype --duphold --removepr NGS/row/bbbb.bam

I execute this command at home directory. 
- Operating system: Ubuntu 20

best regard
![Screenshot from 2020-08-25 20-08-41](https://user-images.githubusercontent.com/62819104/91196018-e245b900-e70e-11ea-8db5-7567ac349c17.png)

**Comment by brentp** [comment]
this is an issue with how you are running docker. you need to mount a local directory for use inside of docker. something like: -v `pwd`:/NGS/`, then change all your NGS paths to the absolute path of /NGS.
