### ISSUE TITLE
Why is the normal sample not filtered for the tumor sample?

### ISSUE THREAD

**Issue by tyyiyi** [brentp/smoove#129]
Hello, I have encountered some problems in detecting structural variation. I hope you can help me. First of all, I have about 50 pairs of samples (NT), all of which have been sequenced by WES. My script is:
      
      $smoove call --outdir $output --name ${tumor}_${normal} --fasta $ref -p 1 --genotype ~/$tumor.MarkDuplicates.bam ~/$normal.MarkDuplicates.bam

Then I filtered the sample:
      
      $bcftools filter -O z -i'FMT/AO[0:0]/FMT/DP[0]>=0.05 && (FMT/AO[1:0]/FMT/DP[1]<0.01 || FMT/ DP[1]=0)' $output/${tumor}_${normal}-smoove.vaf.genotyped.vcf.gz> $smoovefilter/${tumor}_${normal}-smoove.vaf.genotyped. vcf.gz
      $snpsift filter --file $smoovefilter/${tumor}_${normal}-smoove.vaf.genotyped.vcf.gz "(isVariant(GEN[0]))"> $smoovefilter/${tumor}_${ `normal}-smoove.vaf.genotyped.filter.vcf

In the result, I saw a duplicate detected in multiple samples:
An example:
chr16   25055247        398     N       <DUP>   36.47   PASS    SVTYPE=DUP;SVLEN=71161;END=25126408;STRANDS=-+:8;IMPRECISE;CIPOS=-383,29;CIEND=-30,433;CIPOS95=-111,6;CIEND95=-8,74;SU=8;PE=8;SR=0;PRPOS=
3.23627e-15,3.79881e-15,4.4481e-15,5.23987e-15,6.14303e-15,7.21027e-15,8.4526e-15,9.93647e-15,1.16022e-14,1.36108e-14,1.59205e-14,1.86348e-14,2.1821e-14,2.55038e-14,2.97082e-14,3.46619e-14,4.04171e-14,
4.72548e-14,5.51494e-14,6.42427e-14,7.48487e-14,8.70863e-14,1.01181e-13,1.17915e-13,1.37039e-13,1.59549e-13,1.84815e-13,2.14648e-13,2.48592e-13,2.87789e-13,3.33667e-13,3.86242e-13,4.45441e-13,5.13512e-
13,5.93481e-13,6.84284e-13,7.90667e-13,9.1278e-13,1.05341e-12,1.21196e-12,1.3956e-12,1.60521e-12,1.84415e-12,2.12461e-12,2.43945e-12,2.81015e-12,3.22869e-12,3.7116e-12,4.27208e-12,4.90714e-12,5.62766e-
12,6.44689e-12,7.37448e-12,8.44269e-12,9.67163e-12,1.10774e-11,1.26537e-11,1.44869e-11,1.65777e-11,1.89262e-11,2.16834e-11,2.47806e-11,2.83205e-11,3.23597e-11,3.69166e-11,4.21223e-11,4.7932e-11,5.47202
e-11,6.22696e-11,7.09321e-11,8.06301e-11,9.1782e-11,1.04481e-10,1.1889e-10,1.35039e-10,1.53522e-10,1.74153e-10,1.97779e-10,2.24339e-10,2.54307e-10,2.88295e-10,3.26899e-10,3.69978e-10,4.18275e-10,4.7290
9e-10,5.3355e-10,6.01758e-10,6.78515e-10,7.64477e-10,8.62264e-10,9.72982e-10,1.09677e-09,1.23624e-09,1.39138e-09,1.56715e-09,1.76443e-09,1.98333e-09,2.22992e-09,2.50968e-09,2.81888e-09,3.16739e-09,3.55
282e-09,3.97923e-09,4.46063e-09,4.99736e-09,5.60427e-09,6.27879e-09,7.03849e-09,7.87826e-09,8.81363e-09,9.85481e-09,1.10206e-08,1.23205e-08,1.37609e-08,1.53792e-08,1.71636e-08,1.91604e-08,2.14135e-08,2
.38599e-08,2.65747e-08,2.96478e-08,3.29731e-08,3.67475e-08,4.09216e-08,4.55391e-08,5.06636e-08,5.6297e-08,6.2566e-08,6.9377e-08,7.70248e-08,8.54268e-08,9.4739e-08,1.05117e-07,1.16486e-07,1.29025e-07,1.
42659e-07,1.5779e-07,1.74388e-07,1.92602e-07,2.12947e-07,2.35084e-07,2.59442e-07,2.86341e-07,3.16e-07,3.48562e-07,3.84541e-07,4.23453e-07,4.66445e-07,5.13478e-07,5.64971e-07,6.21863e-07,6.84074e-07,7.5
2889e-07,8.27286e-07,9.08527e-07,9.98447e-07,1.09528e-06,1.2023e-06,1.31705e-06,1.4446e-06,1.58114e-06,1.73342e-06,1.8986e-06,2.07632e-06,2.27078e-06,2.48262e-06,2.71314e-06,2.96495e-06,3.23768e-06,3.5
3511e-06,3.85446e-06,4.20274e-06,4.58005e-06,4.98835e-06,5.43577e-06,5.91559e-06,6.43926e-06,7.00065e-06,7.6099e-06,8.26939e-06,8.97418e-06,9.73937e-06,1.05709e-05,1.14592e-05,1.24214e-05,1.3455e-05,1.
45608e-05,1.57556e-05,1.70373e-05,1.84325e-05,1.99075e-05,2.15018e-05,2.32106e-05,2.50452e-05,2.70168e-05,2.91194e-05,3.13505e-05,3.37385e-05,3.63044e-05,3.90446e-05,4.20025e-05,4.51504e-05,4.85262e-05
,5.20902e-05,5.59154e-05,5.99772e-05,6.43011e-05,6.89212e-05,7.38302e-05,7.90491e-05,8.45431e-05,9.04698e-05,9.67377e-05,0.000103288,0.000110309,0.000117694,0.000125565,0.000133927,0.000142658,0.000151
966,0.000161753,0.000172177,0.000183077,0.000194636,0.000206823,0.000219658,0.00023313,0.000247371,0.000262342,0.000277817,0.000294359,0.000311525,0.000329524,0.000348312,0.000368173,0.00038865,0.00041
0294,0.000432817,0.000456459,0.000481192,0.000506837,0.000533547,0.000561404,0.000590615,0.000621293,0.000652962,0.000685814,0.000719938,0.000755302,0.000792021,0.000830324,0.000869733,0.000910567,0.00
0952839,0.000996792,0.00104209,0.00108935,0.00113772,0.00118804,0.00123975,0.0012932,0.00134862,0.00140562,0.00146356,0.00152421,0.00158536,0.00164991,0.00171516,0.00178265,0.00185157,0.00192248,0.0019
9544,0.00206952,0.00214609,0.00222373,0.00230394,0.00238614,0.0024697,0.00255496,0.00264171,0.00273065,0.00282099,0.00291298,0.00300704,0.00310239,0.00319922,0.00329801,0.00339737,0.00349927,0.00360215
,0.0037073,0.00381307,0.00392108,0.0040306,0.0041417,0.00425535,0.00436935,0.00448401,0.0046011,0.00471927,0.00483894,0.00495972,0.00508082,0.00520329,0.00532726,0.00545332,0.00557966,0.00570684,0.0058
3255,0.00595976,0.00608611,0.00621453,0.00634282,0.00647212,0.00660129,0.00673113,0.0068621,0.00699237,0.00712309,0.00725418,0.00738545,0.0075163,0.00764721,0.00777798,0.00790811,0.00803994,0.00817094,
0.00830196,0.00843076,0.00855918,0.00868594,0.00881494,0.00894076,0.00906884,0.00919289,0.00931899,0.00944065,0.00956438,0.00968659,0.0098084,0.00992892,0.0100485,0.0101646,0.0102818,0.0103969,0.010512
5,0.0106265,0.0107373,0.0108476,0.0109555,0.0110654,0.0111724,0.0112787,0.0113828,0.0114846,0.0115877,0.0116883,0.011789,0.0118858,0.0119822,0.0120763,0.0121694,0.01226,0.0123494,0.0124371,0.0125232,0.
0126069,0.0126901,0.0127699,0.0128518,0.0129293,0.0130086,0.0130839,0.0131583,0.0132296,0.0133014,0.013369,0.0134378,0.0135041,0.013569,0.0136323,0.0136953,0.0137548,0.0138146,0.0102043,0.00753731,0.00
556656,0.00411096,0.00303552,0.00224115,0.00165451,0.00122131,0.000901411,0.000665249,0.000490892,0.000266465,0.000144617,7.84858e-05,4.25896e-05,2.31089e-05,1.25387e-05,6.80272e-06,3.69046e-06,2.00189
e-06,7.98705e-07,3.18676e-07,1.27137e-07,5.07197e-08,2.02333e-08,8.07062e-09,3.2192e-09,1.28394e-09,5.12061e-10;PREND=1.60439e-10,3.99092e-10,9.92257e-10,2.46633e-09,6.12905e-09,1.52283e-08,3.78232e-08
,9.39286e-08,2.33178e-07,5.7881e-07,1.43604e-06,3.56215e-06,8.8328e-06,2.18973e-05,5.42667e-05,0.000134454,0.000333059,0.000606647,0.000812602,0.00108812,0.00145652,0.00194926,0.00260749,0.00348749,0.0
0466232,0.0062314,0.00832515,0.0111203,0.0148489,0.0198166,0.0264388,0.0259408,0.0254503,0.0249566,0.0244611,0.0239672,0.0234773,0.0229904,0.0225027,0.0220183,0.0215372,0.0210571,0.0205772,0.020104,0.0
19633,0.0191661,0.0187,0.0182441,0.0177892,0.0173376,0.0168892,0.0164499,0.0160145,0.0155815,0.015154,0.0147378,0.0143286,0.0139204,0.0135153,0.0131197,0.0127344,0.0123539,0.0119809,0.0116123,0.0112537
,0.0109014,0.0105571,0.0102174,0.00988341,0.00955747,0.0092384,0.00892678,0.00862182,0.00832537,0.00803633,0.00775236,0.00747365,0.00720342,0.00694164,0.00668565,0.00643526,0.00619261,0.0059592,0.00573
333,0.00551212,0.00529703,0.00508957,0.00488924,0.00469543,0.00450745,0.00432541,0.0041484,0.00397809,0.0038134,0.00365421,0.00350032,0.00335153,0.00320731,0.0030681,0.00293378,0.00280481,0.00268006,0.
00256017,0.00244451,0.0023334,0.00222665,0.0021232,0.00202423,0.00192867,0.00183765,0.00175024,0.00166706,0.00158721,0.00150943,0.00143577,0.00136497,0.00129757,0.00123237,0.00117026,0.00111148,0.00105
543,0.00100174,0.000950165,0.000901152,0.000854487,0.000809499,0.000766804,0.00072632,0.000687942,0.000651119,0.000615757,0.000582269,0.000550556,0.000520349,0.000491519,0.000464106,0.000438171,0.00041
35,0.000390027,0.000367776,0.000346576,0.000326493,0.000307467,0.000289577,0.000272628,0.00025645,0.000241082,0.00022655,0.000212925,0.000199922,0.000187622,0.000176053,0.000165124,0.000154748,0.000144
952,0.000135771,0.000127138,0.000119005,0.000111304,0.000104073,9.73037e-05,9.09807e-05,8.49595e-05,7.92964e-05,7.3998e-05,6.90847e-05,6.44803e-05,6.01094e-05,5.60102e-05,5.21687e-05,4.85871e-05,4.5232
4e-05,4.20507e-05,3.91103e-05,3.63514e-05,3.37811e-05,3.13741e-05,2.91421e-05,2.70699e-05,2.51261e-05,2.3303e-05,2.15889e-05,1.99984e-05,1.8525e-05,1.71523e-05,1.58687e-05,1.46794e-05,1.35801e-05,1.255
24e-05,1.15941e-05,1.07019e-05,9.87824e-06,9.10902e-06,8.39607e-06,7.73358e-06,7.12164e-06,6.55853e-06,6.0334e-06,5.54776e-06,5.10003e-06,4.68354e-06,4.29826e-06,3.94302e-06,3.61734e-06,3.31959e-06,3.0
4469e-06,2.78981e-06,2.5517e-06,2.33384e-06,2.13506e-06,1.95205e-06,1.78474e-06,1.6299e-06,1.48901e-06,1.36024e-06,1.24073e-06,1.13056e-06,1.02985e-06,9.3817e-07,8.54097e-07,7.7681e-07,7.06718e-07,6.42
333e-07,5.83692e-07,5.29531e-07,4.8043e-07,4.36045e-07,3.95474e-07,3.58448e-07,3.24514e-07,2.93755e-07,2.65888e-07,2.40612e-07,2.17628e-07,1.96644e-07,1.77707e-07,1.60585e-07,1.45166e-07,1.31042e-07,1.
18207e-07,1.06603e-07,9.61544e-08,8.66397e-08,7.79728e-08,7.01976e-08,6.31762e-08,5.68726e-08,5.11106e-08,4.59202e-08,4.12437e-08,3.70317e-08,3.31975e-08,2.96998e-08,2.66022e-08,2.38102e-08,2.13193e-08
,1.90723e-08,1.7045e-08,1.52424e-08,1.36029e-08,1.21377e-08,1.082e-08,9.65653e-09,8.60706e-09,7.66215e-09,6.82778e-09,6.07913e-09,5.41555e-09,4.81811e-09,4.28382e-09,3.80972e-09,3.38647e-09,3.00877e-09
,2.67391e-09,2.3793e-09,2.11288e-09,1.87199e-09,1.65977e-09,1.47275e-09,1.30674e-09,1.15718e-09,1.02325e-09,9.06229e-10,8.02461e-10,7.09685e-10,6.25895e-10,5.52506e-10,4.87842e-10,4.31063e-10,3.81032e-
10,3.36574e-10,2.96556e-10,2.61199e-10,2.29877e-10,2.02021e-10,1.77439e-10,1.55817e-10,1.36931e-10,1.20367e-10,1.05634e-10,9.24086e-11,8.08284e-11,7.06861e-11,6.17425e-11,5.38869e-11,4.70363e-11,4.1096
7e-11,3.58926e-11,3.1248e-11,2.72345e-11,2.37454e-11,2.06946e-11,1.79912e-11,1.56577e-11,1.3617e-11,1.18792e-11,1.03227e-11,8.94996e-12,7.77631e-12,6.76339e-12,5.87484e-12,5.0948e-12,4.42524e-12,3.8458
9e-12,3.33789e-12,2.89382e-12,2.50448e-12,2.16902e-12,1.87924e-12,1.62714e-12,1.40794e-12,1.21724e-12,1.05299e-12,9.11473e-13,7.87983e-13,6.8171e-13,5.86677e-13,5.06352e-13,4.36786e-13,3.75828e-13,3.22
497e-13,2.77298e-13,2.39977e-13,2.07222e-13,1.78443e-13,1.53179e-13,1.317e-13,1.13543e-13,9.76624e-14,8.34951e-14,7.1299e-14,6.1106e-14,5.24044e-14,4.49001e-14,3.83415e-14,3.28285e-14,2.80893e-14,2.400
36e-14,2.03981e-14,1.73285e-14,1.47945e-14,1.26414e-14,1.07425e-14,9.11817e-15,7.75994e-15,6.60031e-15,5.61197e-15,4.75339e-15,4.03157e-15,3.4233e-15,2.9064e-15,2.46223e-15,2.07768e-15,1.75786e-15,1.48
294e-15,1.25569e-15,1.06334e-15,8.99631e-16,7.57114e-16,6.36187e-16,5.32517e-16,4.45182e-16,3.71631e-16,3.10198e-16,2.60445e-16,2.19343e-16,1.83764e-16,1.52933e-16,1.27116e-16,1.05408e-16,8.69052e-17,7
.24141e-17,6.04394e-17,5.0597e-17,4.2122e-17,3.48879e-17,2.9099e-17,2.41829e-17,1.99903e-17,1.64535e-17,1.36878e-17,1.14343e-17,9.45112e-18,7.82826e-18,6.40981e-18,5.2449e-18,4.28598e-18,3.5367e-18,2.9
1237e-18,2.3678e-18,1.90721e-18,1.55151e-18,1.28172e-18,1.05206e-18,8.47163e-19,6.88024e-19,5.62443e-19,4.62397e-19,3.70763e-19,2.95075e-19,2.39651e-19,1.95192e-19,1.57711e-19,1.25233e-19,1.00059e-19,8
.02665e-20,6.39775e-20,4.99895e-20,3.84306e-20,3.02951e-20,2.38686e-20,1.84738e-20,1.40705e-20,1.07422e-20,8.22356e-21,6.2723e-21,4.6933e-21,3.54745e-21,2.69503e-21,2.05344e-21,1.52553e-21,1.13157e-21,
8.56492e-22,6.20815e-22,4.4753e-22,3.18789e-22,2.34818e-22,1.70987e-22,1.23879e-22,8.66922e-23,5.94317e-23,4.06397e-23,2.6715e-23,1.78902e-23,1.16772e-23,7.47814e-24,4.57743e-24,2.89175e-24,1.74691e-24
,9.44682e-25,4.83423e-25,2.21815e-25,9.50043e-26,3.19909e-26;AC=1;AN=4       GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB   0/1:31:36.47:-5,-2,-5:67:59:7:59:7:0:0:0:59:7:0.11      0/0:112:0:-1,-12,-21
:123:123:0:122:0:76:0:0:46:0:0

However, when I verified this structural variation, I found that it was not a repeat. The nine hundred bases before and after the two breakpoints were similar sequences, which caused alignment problems.Why didn't the normal samples here filter the tumor samples to remove this false positive structural variation?
chr16   25055251        311     N       <DUP>   46.69   PASS    SVTYPE=DUP;SVLEN=71202;END=25126453;STRANDS=-+:7;IMPRECISE;CIPOS=-453,29;CIEND=-30,390;CIPOS95=-130,3;CIEND95=-9,67;SU=7;PE=7;SR=0;PRPOS=……（too long, not pasted）
;AC=1;AN=4
       GT:GQ:SQ:GL:**DP:RO:AO**:QR:QA:RS:AS:ASC:RP:AP:AB   0/1:5:46.69:-5,-1,-1:**27:21:5**:21:5:0:0:0:21:5:0.19       0/0:55:0:-0,-6,-11:**62:61:0**:60:0:35:0:0:25:0:0

And, in another pair of samples where this duplication was detected, the AO of the normal sample was 0, but when I used IGV visualization, there was a pair_end reads that supported the duplication. Why was the AO not 1?

![image](https://user-images.githubusercontent.com/48273651/92363995-f6cd7c80-f124-11ea-81c7-c77c8a18da21.png)

Thank you!
Tang

**Comment by brentp** [comment]
Hi, smoove uses existing tools and tries to improve the experience of calling SVs. But this is more a question for lumpy or svtyper. I am not sure why that read was not called as evidence in the normal sample. What is the mapping quality?
