### ISSUE TITLE
Filter out low quality calls

### ISSUE THREAD

**Issue by cagaser** [brentp/smoove#138]
Hello, 

Thank you for developing smoove. 
I am trying to merge calls from different callers, including smoove. 
I'd like to know how I can filter calls that are of low quality/false positives before merging. 
Looking at the output VCF header, I don't see any filtering done. 
I only see Phred score in the QUAL field. Should I be using this instead, e.g. >30? 

I ran smoove as follow: 

```
smoove call \
--outdir ~{outputDir} \
--name ~{sample} \
--fasta ~{referenceFasta} \
--removepr \
--genotype \
~{bamFile}
```

**Comment by brentp** [comment]
Hi, you should run `smoove call` with `--genotype` and `-d` (for duphold) unless you have good reason not to.
You will then be able to filter on duphold annotations. See #130 for example of help on filtering with [slivar](https://github.com/brentp/slivar)

**Comment by cagaser** [comment]
Hi brentp, 

Thank you for the recommendation.
It's a great tool! I also applied it to Delly and it properly reported all false positives. 
I will also try to apply this to the other callers (clever and manta) before merging.

**Comment by brentp** [comment]
glad to hear it!
