### ISSUE TITLE
tag not defined error in 0.1.3

### ISSUE THREAD

**Issue by chapmanb** [brentp/smoove#14]
Brent;
Thanks for the latest update. I've been working on getting smoove integrated with bcbio and running into an issue where it dies after finishing up calling and I'm not totally sure what is happening:
```
[smoove] 2018/03/28 12:34:40 Reading library metrics from /mnt/work/cwl/bcbio_validation_workflows/NA24385-sv/debug_smoove/tempclean-604417735/360058017svtype-lib...
[smoove] 2018/03/28 12:34:40  done
[smoove] 2018/03/28 12:47:26 The tag "1" is not defined in (null)
[smoove] 2018/03/28 12:47:26 wrote sorted, indexed file to /mnt/work/cwl/bcbio_validation_workflows/NA24385-sv/debug_smoove/NA24385-svs-smoove.genotyped.vcf.gz
panic: exit status 255

goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(0x9e74e0, 0xc420194080)
        /home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:32 +0x4a
github.com/brentp/smoove/svtyper.Svtyper(0x9e7000, 0xc42000e108, 0x7ffd9997f1cb, 0x5c, 0xc42011e590, 0x1, 0x1, 0x7ffd9997f244, 0x40, 0x7ffd9997f22f, ...)
        /home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:209 +0xbc1
github.com/brentp/smoove/lumpy.Main()
        /home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:286 +0x3fb
main.main()
        /home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:106 +0x17f
```
`The tag "1" is not defined` error seems most diagnostic but I'm not sure what do do about it. I put together a reproducible test case here that demonstrates the problem for me:

https://s3.amazonaws.com/chapmanb/testcases/smoove_tagdefined.tar.gz

Thanks so much for any suggestions/tips to debug.

**Comment by brentp** [comment]
I see the problem. The bcftools annotate has `-c 1` which only makes sense for bcftools view. Will make a new release shortly.

**Comment by brentp** [comment]
do you mind if I add this as a test-case for the smoove repo?

**Comment by chapmanb** [comment]
Oh sweet, thanks for catching the underlying issue; I was totally confused. You can definitely use as a test case, thanks so much for helping with the fix.

**Comment by brentp** [comment]
this is fixed in master.

**Comment by chapmanb** [comment]
Sweet, thanks Brent. Any chance of a new release so I can sync up the conda package with this as well? Much appreciated.

**Comment by brentp** [comment]
yes, just waiting on #13 . but I'll definitely put out a new release by tomorrow morn.

**Comment by chapmanb** [comment]
Sounds great, thanks again.

**Comment by brentp** [comment]
new release is out. thanks for reporting and for the test-case!
