### ISSUE TITLE
smoove/paste + singularty + 1185 vcfs: argument list too long

### ISSUE THREAD

**Issue by lindenb** [brentp/smoove#151]
Hi @brentp 

I'm trying to use smoove/paste with singularity and 1185 bams. I got an error 

> argument list too long

it's not clear to me if the problem comes from bash/singularity/smoove.

1) is it possible to use a divide-and-conquer strategy with `paste` ? :  paste vcfs 1-100, paste vcfs 101-200, paste vcfs 201-300, etc... and then paste the merged vcfs ?

2)  Am I wrong ? smoove doesn't support a `.list` extension like you did here : https://github.com/brentp/somalier/issues/37#issuecomment-550502468 ?

thank you again for your help :-)

**Comment by lindenb** [comment]
answering my own question: using a divide-and-conquer strategy worked. (however I'm not sure if the INFO fields were correctly merged).

**Comment by brentp** [comment]
Hi Pierre, yes, I should add support for a .list argument here. Would love to get a PR to that effect. Otherwise, I'll leave this open til I have a chance to implement.

**Comment by brentp** [comment]
Hi Pierre, I wonder if using `bcftools merge` with `-m none` makes it faster?
