### ISSUE TITLE
Using CRAM instead of BAM when genotyping samples for SVs?

### ISSUE THREAD

**Issue by Saeideh-Ashouri** [brentp/smoove#153]
Hello.

I have done SV calling using smoove but I do not have enough disk space for storing BAM files for a large number of samples I am working with (12,500 samples). Is it possible to use CRAM files instead when genotyping them for SVs?

Thank you in advance,
Best,
Saeideh

**Comment by brentp** [comment]
Hi Saeideh, crams will work fine with smoove.
