### ISSUE TITLE
smoove docker version:  ([E]lumpy-filter)

### ISSUE THREAD

**Issue by nitha26** [brentp/smoove#156]
@brentp 
I'm running lumpy via smoove in docker version for SV calling (short reads). For test run I had taken 4 bam  files and executed smoove using following command. 

`smoove call -x --name my_cohort -exclude ../exclude_reg/exclude.cnvnator_100bp.GRCh38.20170403.bed --fasta ../ref-gen/GRCh38_full_analysis_set_plus_decoy_hla.fa -p 36 --genotype *.bam --outdir /root/work_output/`

I have two questions:

1. I get to see this line in output run  **([E]lumpy-filter)**  is  this anything to worry, what does this indicates?  
But the job had completed by generating output (my_cohort-smoove.genotyped.vcf.gz)  

![lumpy_filter_smoove](https://user-images.githubusercontent.com/29456358/123921100-49be3c00-d9a4-11eb-9eb9-2100982cf22d.png)

2. While doing population level or with few samples (lets say 1-5 samples), in which step I can retrieve sample level (individual) SVcalled vcf files. I would like to check types and counts of  SVs for each samples (before consensus file)? Because  while running traditional lumpy, we get  individual samples VCF, then we do mergeing.  

Could you please help me how to use smoove efficiently. Thanks.

**Comment by brentp** [comment]
1. The just means it's information from the lumpy-filter stderr looks OK.
2. You can count genotypes or you can run smoove according to the [population calling instructions](https://github.com/brentp/smoove#population-calling)

**Comment by nitha26** [comment]
@brentp Thank you i will look in to that.
