### ISSUE TITLE
([E]lumpy-filter) mv: cannot stat ‘SmooveTest_out/001MS.split.bam.tmp.bam’: No such file or directory

### ISSUE THREAD

**Issue by nitha26** [brentp/smoove#158]
Hi @brentp, I am running smoove in conda version in cluster. When I try to do test run for 10 samples (CRAM file ) in parallel getting following error   

Command used in python:
`smoove call --outdir SmooveTest_out --exclude exclude_reg/exclude.cnvnator_100bp.GRCh38.20170403.bed --name "+x[int]+" --fasta ref-gen/GRCh38_full_analysis_set_plus_decoy_hla.fa -p 1 --genotype CRAM/"+x[int]+".cram `  

`[smoove] 2021/07/05 12:39:25 calculating bam stats for 1 bams
[smoove] 2021/07/05 12:39:29 done calculating bam stats
[smoove]: ([E]lumpy-filter) 2021/07/05 13:27:07 mv: cannot stat ‘SmooveTest_out/001MS.split.bam.tmp.bam’: No such file or directory
[smoove]:2021/07/05 13:27:07 finished process: lumpy-filter (lumpy_filter -f ref-gen/GRCh38_full_analysis_set_plus_decoy_hla.fa CRAM/001MS.cram SmooveTest_out/00) in user-time:47m18.254711s system-time:21.227666s
[smoove]:2021/07/05 13:27:07 error running command: lumpy_filter -f ref-gen/GRCh38_full_analysis_set_plus_decoy_hla.fa CRAM/001MS.cram SmooveTest_out/001MS.split.bam.tmp.bam SmooveTest_out/001MS.disc.bam.tmp.bam 2 && mv SmooveTest_out/001MS.split.bam.tmp.bam SmooveTest_out/001MS.split.bam && mv SmooveTest_out/001MS.disc.bam.tmp.bam SmooveTest_out/001MS.disc.bam -> exit status 1
panic: exit status 1

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7fffa7423c68, 0x5, 0x7fffa7423c76, 0x32, 0x7fffa7423c11, 0xe, 0xc420131430, 0x1, 0x1, 0xc420197f40, ...)
        /home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:115 +0x556
github.com/brentp/smoove/lumpy.Main()
        /home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:275 +0x23a
main.main()
        /home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:115 +0x1dd
m/brentp/smoove/cmd/smoove/smoove.go:115 +0x1dd`

Could you please help me?
Thanks!

**Comment by brentp** [comment]
Hi, here are some things you can check:
1. if this has run before remove all stale files in `SmooveTest_out`
2. make sure that the process has permission to create and write to `SmooveTest_out`
3. check if the cram file that is erroring is very small or check if it is not readable.

**Comment by nitha26** [comment]
@brentp,I tried re-running smoove (docker version running in HPC) this time in bash script after the above correction for 7 cram files. But this time I'm facing different types of errors. The error file is attached.
[smoove_7samptestrunLog.txt](https://github.com/brentp/smoove/files/6774862/smoove_7samptestrunLog.txt)

Command used:  
```
#!/bin/bash  
FILES="/gpfs/data/SV_test/smoove_SVcalling/CRAM/*.cram"; for f in $FILES; do smoove call --outdir /gpfs/data/SV_test/smoove_SVcalling/7_out/ --exclude /gpfs/data/SV_test/smoove_SVcalling/exclude_reg/exclude.cnvnator_100bp.GRCh38.20170403.bed **--name "$f"_new** --fasta /gpfs/data/SV_test/smoove_SVcalling/ref-gen/GRCh38_full_analysis_set_plus_decoy_hla.fa -p 1 **--genotype "$f"**  &>>smoove_Test7cram; done
```
I have a doubt in the output step ($sample-smoove.genotyped.vcf.gz). i.e. In population level, if we run Stepl1 command for 100 samples, then whether we get 100 individual "*.smoove.genotyped.vcf.gz" or a single joint "genotype.vcf.gz"?

Could you please guide me whether the command used is correct.  

Thanks!

**Comment by brentp** [comment]
Hi, please update to the latest version of smoove and re-try with clean directories.
You have a very old version of smoove.

**Comment by nitha26** [comment]
Thank you. I will check it

**Comment by nitha26** [comment]
@brentp could you please redirect me to the link  where I can find the latest **docker version** of smoove. Thanks

**Comment by brentp** [comment]
https://www.google.com/search?q=docker+smoove
