### ISSUE TITLE
Is there any installation guide for this smoove package ?

### ISSUE THREAD

**Issue by Navin-techi** [brentp/smoove#161]
hi @brentp,
Is there any installation guide where I can implement this on the cluster for parallel processing on centos?

Thanks in advance.

**Comment by brentp** [comment]
Hi, you can use docker (singularity) or conda to install smoove.

**Comment by yqlan** [comment]
> Hi, you can use docker (singularity) or conda to install smoove.

@brentp 
Hi, I installed smoove using singularity, `singularity build smoove.sif docker://brentp/smoove`
but it is not the latest version that was installed, it is version 0.2.6

**Comment by brentp** [comment]
Hi, I pushed the newer versions to dockerhub now.

**Comment by yqlan** [comment]
> Hi, I pushed the newer versions to dockerhub now.

Hi @brentp ,
 thanks for your reply, it seems version 0.2.8 is still 0..2.6.

command:
`singularity build smoove.sif docker://brentp/smoove:v0.2.8`
`singularity exec smoove.sif smoove call --help`

output:
`[smoove] 2024/06/17 20:17:30 starting with version 0.2.6
this runs lumpy ands sends output to {outdir}/{name}-smoove.vcf.gz if --genotype is requested, the output goes to {outdir}/{name}-smoove.genotyped.vcf.gz
Usage: smoove --name NAME --fasta FASTA [--exclude EXCLUDE] [--excludechroms EXCLUDECHROMS] [--processes PROCESSES] [--outdir OUTDIR] [--noextrafilters] [--support SUPPORT] [--genotype] [--duphold] [--removepr] BAMS [BAMS ...]

Positional arguments:
  BAMS                   path to bam(s) to call.

Options:
  --name NAME, -n NAME   project name used in output files.
  --fasta FASTA, -f FASTA
                         fasta file.
  --exclude EXCLUDE, -e EXCLUDE
                         BED of exclude regions.
  --excludechroms EXCLUDECHROMS, -C EXCLUDECHROMS
                         ignore SVs with either end in this comma-delimited list of chroms. If this starts with ~ it is treated as a regular expression to exclude. [default: hs37d5,~:,~^GL,~decoy]
  --processes PROCESSES, -p PROCESSES
                         number of processors to parallelize. [default: 3]
  --outdir OUTDIR, -o OUTDIR
                         output directory.
  --noextrafilters, -F   use lumpy_filter only without extra smoove filters.
  --support SUPPORT, -S SUPPORT
                         mininum support required to report a variant. [default: 4]
  --genotype             stream output to svtyper for genotyping
  --duphold, -d          run duphold on output. only works with --genotype
  --removepr, -x         remove PRPOS and PREND tags from INFO (only used with --gentoype).
  --help, -h             display this help and exit`

**Comment by brentp** [comment]
Hi, sorry for the problems. Indeed it was building the 0.2.8 docker image with 0.2.6. I have updated the image. Not sure how caching works for singularity, but I have checked that the docker image now contains v0.2.8 and I pushed it to dockerhub.

**Comment by yqlan** [comment]
> Hi, sorry for the problems. Indeed it was building the 0.2.8 docker image with 0.2.6. I have updated the image. Not sure how caching works for singularity, but I have checked that the docker image now contains v0.2.8 and I pushed it to dockerhub.

Hi @brentp, Thanks, Works now
