### ISSUE TITLE
Population level caling: Genotype Step concept & Merging step

### ISSUE THREAD

**Issue by nitha26** [brentp/smoove#163]
Hi @brentp could you please explain 1. how this #160 squaring concept is applied in **population level** or when we don't use trios  (I understand squaring concept in trios)? 

2. And how can I filter out only PASS variants from end VCF file (completion of all steps in population level calling) ? could  you help me to filter out PASS variants for next level analysis?

3. Whether smoove **support genotyping**  of other tools SVs VCF file (Manta VCF, GRIDSS VCF)?

4. Can smoove do merging step for creating consensus file? eg (Delly VCF + smoove VCF = ConsensusSVcall?  

Thanks a lot!

**Comment by brentp** [comment]
Hi,
1. I have explained this as best I can. This is commonly done for SNPs and indels as well as for SVs. 
2. you can use bcftools to do this type of filtering.
3. no
4. no
