### ISSUE TITLE
Feature Request: allow tmpdir specification

### ISSUE THREAD

**Issue by JohnUrban** [brentp/smoove#172]
Hi all,

Thanks for the great program. Super easy to use. Seriously.

I ran into a problem with a large BAM file.

```

panic: write /tmp/smoove-mosdepth-bam175073159: no space left on device

goroutine 11151 [running]:
github.com/brentp/smoove/lumpy.check(...)
	/home/brentp/src/smoove/lumpy/lumpy.go:54
github.com/brentp/smoove/lumpy.remove_sketchy(0xc000030340, 0x33, 0x3e8, 0x7fffaace6523, 0x53, 0x0, 0x0, 0xc000189900, 0x4, 0x4, ...)
	/home/brentp/src/smoove/lumpy/depthfilter.go:323 +0x17dd
github.com/brentp/smoove/lumpy.remove_sketchy_all.func1(0xc00013a5a0, 0x3e8, 0x7fffaace6523, 0x53, 0x0, 0x0, 0xc000189900, 0x4, 0x4, 0x1, ...)
	/home/brentp/src/smoove/lumpy/depthfilter.go:399 +0x231
created by github.com/brentp/smoove/lumpy.remove_sketchy_all
	/home/brentp/src/smoove/lumpy/depthfilter.go:397 +0x194
```

I've seen this kind of error before with other software/programs on the cluster I'm using. Specifically:
```
panic: write /tmp/smoove-mosdepth-bam175073159: no space left on device
```

Apparently this is because the IT in charge of maintaining the cluster has allotted very little space to /tmp. 

Sometimes programs have an option like `--tmpdir` that allows the user to specify a directory explicitly for tmp files. Tjhat would probably solve my issue here.

If you see a work-around, please let me know. The obvious one would be use a different system. Let's pretend that's not possible at the moment.

Thanks for reading. 

Best,

John

**Comment by brentp** [comment]
Hi John,
you can use, for example,
```
export TMPDIR=/somewhere/else/
smoove ...
```

**Comment by JohnUrban** [comment]
Well don't I feel silly. 

Thanks for the tip!

Closing.
