### ISSUE TITLE
Missing libcrypto.so.1.0.0 hack.

### ISSUE THREAD

**Issue by JohnUrban** [brentp/smoove#173]
This is just a helpful tip for future googlers and issue searchers.

I installed smoove via conda on two different systems:
```
conda create -n smoove -c bioconda -y smoove
```

It worked like a charm on one, but raised an error on the other. The error (cleaned up a bit):
```
[smoove] 2021/10/01 03:10:40 starting with version 0.2.8
[smoove] 2021/10/01 03:10:40 calculating bam stats for 1 bams
[smoove]: ([E]lumpy-filter) 2021/10/01 03:10:40 lumpy_filter: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

....

[smoove] 2021/10/01 03:10:44 done calculating bam stats
panic: exit status 127
```

I tried a few workarounds with conda, but nothing worked.

This did though.

Step 1: Locate libcrypto.so.1.0.0 on your system.
```
locate libcrypto.so.1.0.0

#or 
sudo locate libcrypto.so.1.0.0
```

Step 2: copy it into your `smoove` ENV `lib` folder
```
cp /var/lib/snapd/snap/core/11606/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 ~/software/conda/anaconda3/envs/smoove/lib/
```

Step 3: Run smoove and smile as it now works.

Note - my system had 3 locations for `libcrypto.so.1.0.0`. I just picked one to copy.
This solved the issue for me.
Hope it works for you as well.

Best,

John

p.s. feel free to close any time.

**Comment by brentp** [comment]
cheers, I've hit this myself.
