### ISSUE TITLE
SVTyper Unknown argument

### ISSUE THREAD

**Issue by janawold1** [brentp/smoove#176]
Hello, 
I have installed smoove through the bioconda repo. I used to run v2.6, but started having some merge issues and decided to upgrade. However, I now get the error below across the 3 latest versions of smoove. 

An example of the error is below:
`smoove call --name AU01 --outdir smoove/SVcalls/ --fasta reference/bSteHir1.pri.cur.20190820.fasta --genotype alignments/merged_bam/AU01.bam`

[smoove] 2021/10/15 17:54:46 Super_scaffold_1   1000000
[smoove] 2021/10/15 17:54:46 > gsort version 0.1.4
[smoove] 2021/10/15 17:54:46 Calculating library metrics from alignments/merged_bam/AU01.bam...
[smoove] 2021/10/15 17:54:58 Super_scaffold_2   1000000
[smoove] 2021/10/15 17:55:11  done
Writing library metrics to /tmp/tempclean-366548679/333575853svtype-lib...
[smoove] 2021/10/15 17:55:11  done
[smoove] 2021/10/15 17:55:11 usage: svtyper [-h] [-i FILE] [-o FILE] -B FILE [-T FILE] [-l FILE] [-m INT]
               [-n INT] [-q] [--max_reads INT] [--split_weight FLOAT]
               [--disc_weight FLOAT] [-w FILE]
[smoove] 2021/10/15 17:55:11 usage: svtyper [-h] [-i FILE] [-o FILE] -B FILE [-T FILE] [-l FILE] [-m INT]
               [-n INT] [-q] [--max_reads INT] [--split_weight FLOAT]
               [--disc_weight FLOAT] [-w FILE]
[smoove] 2021/10/15 17:55:11 svtyper: error: unrecognized arguments: --max_ci_dist 0
[smoove] 2021/10/15 17:55:11 svtyper: error: unrecognized arguments: --max_ci_dist 0
[smoove] 2021/10/15 17:55:11 usage: svtyper [-h] [-i FILE] [-o FILE] -B FILE [-T FILE] [-l FILE] [-m INT]
               [-n INT] [-q] [--max_reads INT] [--split_weight FLOAT]
               [--disc_weight FLOAT] [-w FILE]
[smoove] 2021/10/15 17:55:11 svtyper: error: unrecognized arguments: --max_ci_dist 0
panic: exit status 2

goroutine 31081 [running]:
github.com/brentp/smoove/svtyper.check(...)
        /home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper.func2(0xc001e7a000, 0xc000121600, 0x1, 0x1, 0x7ffe15c2227e, 0x29, 0xc001e7c0c0, 0x2c, 0xc001d7ab48, 0xc001d7ab60, ...)
        /home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:179 +0x90b
created by github.com/brentp/smoove/svtyper.Svtyper
        /home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:165 +0xab2

**Comment by brentp** [comment]
Hi, you must have a very old version of svtyper. You should be able to run `svtyper -h` and see this in the help:
```
  --max_ci_dist INT     maximum size of a confidence interval before 95% CI is used intead (default: 1e10)
```

and you can also see the version in the output, it should be v0.7.0.

**Comment by user-tq** [comment]
I met the same problem，because i install smoove  from conda，It's like a prank。conda install all softs，but the svtyper cant be used.
finally, i run this cmd to install newst version by conda，Now it runs smoothly.
```
conda install  smoove=0.2.8  -c bioconda
conda install  svtyper=0.7.1  -c bioconda
```
