### ISSUE TITLE
Smoove for WES

### ISSUE THREAD

**Issue by alisaadat922** [brentp/smoove#182]
Hello

I want to use Smoove for whole exome sequencing data. It is mentioned that Smoove could be used for exome data https://github.com/brentp/smoove/issues/89 

However, the author of Lumpy has mentioned that Lumpy is not designed for exome data: https://github.com/arq5x/lumpy-sv/issues/225#issuecomment-355760390

Overall, do you recommend using Smoove for exome data? If no, can you recommend other tools?

Thank you for the amazing tools!
Ali

**Comment by brentp** [comment]
Hi, smoove will work on exome data (as will lumpy) but it's probably not the best choice. I don't know what the best tools are for exome but I have found those that rely on a population database of existing samples (to track previously seen variability) will work the best.
