### ISSUE TITLE
SV lengths

### ISSUE THREAD

**Issue by dcf774967** [brentp/smoove#187]
Hi!When i check the smoove result. I find the DUP length is so large! I don't know why! 
Could somebody HELP me!
`chr1LG6 13106184        1330202 N       <DUP>   23.44   .       SVTYPE=DUP;SVLEN=251422240;END=264528424;STRANDS=-+:242;CIPOS=-2,2;CIEND=-2,2;CIPOS95=0,0;CIEND95=0,0;SU=242;PE=0;SR=242;SNAME=JI1539:9601,JI1093:5324,JI1980:3252,JI2348:2994,JI0058:2905,JI0328:7438,JI0015:4584,JI2083:6297,JI1092:5342,JI1794:5544,JI0083:3926,JI1094:5078,JI1088:5669,JI2517:7324,JI1491:5591,JI0132:5445,JI2548:5525,JI2350:5435,JI1585:4140,JI2530:6907,JI1587:3901,JI3511:4328,JI1313:4199,JI3604:3388,JI0932:5457,JI1542:7941,JI1469:5915,JI3148:5486,JI1132:3599,JI3159:5834,JI1626:3375,JI3157:5419,JI1395:3143,JI2115:5358,JI2698:6670,JI3156:5585,JI0554:3308,JI1084:3914,JI0268:3841;ALG=PROD;GCF=0.309327    GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB:DHFC:DHFFC:DHBFC  0/1:23:23.44:-4,-2,-4:53:46:6:45:5:28:2:0:17:2:0.1:0.764706:0.8125:0.764706`
Thank you very  much!

**Comment by brentp** [comment]
That's a spurious call. That happens sometimes, but this one has low quality, low support and no evidence from duphold annotations (DH*)

**Comment by dcf774967** [comment]
> 
Hi,brentp!
How should I filter these spurious calls to get high quality SV results?
It is very important to me!
![image](https://user-images.githubusercontent.com/60096719/153322899-1add54ba-1095-43e1-ad1a-b6f207de3ace.png)
In other words, how should I filter the results of the third step, because the results of this step need to be used to merge later.
Thanks a lot for your reply!

**Comment by brentp** [comment]
I would just filter them after the final step.

**Comment by dcf774967** [comment]
> I would just filter them after the final step.

Thanks a lot! I will try.
brentp.
           --zcf
