### ISSUE TITLE
lumpy_filter must be in default PATH, regardless of current env

### ISSUE THREAD

**Issue by dmckean** [brentp/smoove#19]
I'm seeing an issue on macOS and REHL where `smoove call`, is not able to execute `lumpy_filter`  because it's missing from `PATH` in the shell env created by `shpool`. In these cases, I have `lumpy_filter` symlinked into a directory that I added to PATH in `.bash_profile`. `lumpy_filter` passes the `HasProg` check.

I've only had success after symlinking `lumpy_filter` into the current directory or into a location in the system-defined PATH. Changes to PATH exported in the current env or at login are not effective. 

The issue occurrs when the filter process is submitted to `shpool.Pool` and eventually executed. shpool runs each filter in a separate, non-interactive, non-login shell with an env of two k-v pairs ([shpool.go:L158-182](https://github.com/brentp/go-athenaeum/blob/master/shpool/shpool.go#L158-L182)). While those two k-v pairs are added via `p.c.Env = append(p.c.Env, fmt.Sprintf("CPUs=%d", p.p.CPUs))` , the initial `p.c.Env` is empty. Appending the k-v pairs to `p.c.Env` overrides the [default behavior](https://golang.org/pkg/os/exec/#Cmd) for Env, where Env is set to the Env of the parent process iff Env is nil.

I don't see shpool used elsewhere in smoove. Other `exec.Command("bash", "-c", cmd)` invocations don't seem to have a problem as they leave `Env` untouched.

Invocations like `exec.Command("samtools", ...)` work fine since the first arg is passed on to `exec.LookPath`, much like the checks done by `HasProg()`.

I've submitted a pull request that resolves lumpy_filter prior to submitting the process to the pool. 

Another approach may be modifying `shpool` to establish the default env (either the parent env at pool creation or per-process at process submission). This seems a bit more troublesome if `shpool` is being used in places that might be altering and responding to env variables.

---

### HasProg checks

```{bash}
$ smoove
smoove version: 0.1.10

smoove calls several programs. Those with 'Y' are found on your $PATH. Only those with '*' are required.

 *[Y] bgzip [ sort   -> (compress) ->   index ]
 *[Y] gsort [(sort)  ->  compress   ->  index ]
 *[Y] tabix [ sort   ->  compress   -> (index)]
 *[Y] lumpy
 *[Y] lumpy_filter
 *[Y] samtools [only required for CRAM input]

  [Y] mosdepth [extra filtering of split and discordant files for better scaling]
  [Y] svtyper [required to genotype SV calls]
  [Y] svtools [only needed for large cohorts].

...
```

### Can't find lumpy_filter
```{bash}
$ smoove call --name samp1 --fasta hg19.fa --outdir smoove_output input.bam
[smoove] 2018/07/03 17:10:40 starting with version 0.1.10
[smoove] 2018/07/03 17:10:40 calculating bam stats for 1 bams
[smoove]: ([E]lumpy-filter) 2018/07/03 17:10:40 /bin/bash: lumpy_filter: command not found
[smoove]:2018/07/03 17:10:40 finished process: lumpy-filter (lumpy_filter -f hg19.fa input.bam smoove_output/LP6005118-DNA_A10.split.bam.tmp.bam smoove_output/LP) in user-time:2.169ms system-time:4.477ms
[smoove]:2018/07/03 17:10:40 error running command: lumpy_filter -f hg19.fa input.bam smoove_output/LP6005118-DNA_A10.split.bam.tmp.bam smoove_output/LP6005118-DNA_A10.disc.bam.tmp.bam 2 && mv smoove_output/LP6005118-DNA_A10.split.bam.tmp.bam smoove_output/LP6005118-DNA_A10.split.bam && mv smoove_output/LP6005118-DNA_A10.disc.bam.tmp.bam smoove_output/LP6005118-DNA_A10.disc.bam -> exit status 127
[smoove] 2018/07/03 17:10:42 done calculating bam stats
panic: exit status 127

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7ffeefbff8b3, 0x5, 0x7ffeefbff8c1, 0x7, 0x7ffeefbff8d2, 0xd, 0xc4200a74c0, 0x1, 0x1, 0xc420198140, ...)
	/Users/dave/local/go/src/github.com/brentp/smoove/lumpy/lumpy.go:115 +0x556
github.com/brentp/smoove/lumpy.Main()
	/Users/dave/local/go/src/github.com/brentp/smoove/lumpy/lumpy.go:275 +0x23a
main.main()
	/Users/dave/local/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:115 +0x1dd
```

**Comment by brentp** [comment]
Hi David, so is it correct to summarize that making the update to shpool that you indicate is the simplest fix?
Sorry for the delay. I have been on vacation.

**Comment by brentp** [comment]
my local shpool had an unstaged change that added `os.Environ()` to each env so that's probably why I wasn't see this. I pushed that change now. Thanks for finding this. Let me know if that resolves it for you.

**Comment by dmckean** [comment]
Hi Brent, the commit adding `os.Environ()` to shpool should fix it, that's what I was doing locally after my update. Closing #20 

Finding smoove was a typical situation where I needed to improve my lumpy workflow, and eventually saw your awesome work here. Nice job.

**Comment by dfermin** [comment]
Hi
I'm getting the same error with the latest github download of smoove.

Here is my command:
`smoove call --outdir $PWD/results-call --name SAFID_031 --fasta /data/genome/hs37d5.fa -p 1 bam.files/samp_031.chr11.bam`

Here is the standard out I get:
```
[smoove] 2019/01/11 11:14:42 starting with version 0.2.2
[smoove] 2019/01/11 11:14:42 calculating bam stats for 1 bams
[smoove] 2019/01/11 11:14:56 done calculating bam stats
[smoove]: ([E]lumpy-filter) 2019/01/11 11:15:04 [lumpy_filter] extracted splits and discordants from 29274188 total aligned reads
[smoove]:2019/01/11 11:15:04 finished process: lumpy-filter (set -eu; lumpy_filter -f /data/genome/hs37d5.fa bam.files/samp_031.chr11.bam /home/dfermin/cnvProj) in user-time:52.597445s system-time:2.421624s
[smoove]:2019/01/11 11:15:04 error running command: set -eu; lumpy_filter -f /data/genome/hs37d5.fa bam.files/samp_031.chr11.bam /home/dfermin/cnvProject/cnv/smoove/results-call/samp_031.split.bam.tmp.bam /home/dfermin/cnvProject/cnv/smoove/results-call/samp_031.disc.bam.tmp.bam 2 && mv /home/dfermin/cnvProject/cnv/smoove/results-call/samp_031.split.bam.tmp.bam /home/dfermin/cnvProject/cnv/smoove/results-call/samp_031.split.bam && mv /home/dfermin/cnvProject/cnv/smoove/results-call/samp_031.disc.bam.tmp.bam /home/dfermin/cnvProject/cnv/smoove/results-call/samp_031.disc.bam && cp /home/dfermin/cnvProject/cnv/smoove/results-call/samp_031.split.bam /home/dfermin/cnvProject/cnv/smoove/results-call/samp_031.split.bam.orig.bam && cp /home/dfermin/cnvProject/cnv/smoove/results-call/samp_031.disc.bam /home/dfermin/cnvProject/cnv/smoove/results-call/samp_031.disc.bam.orig.bam -> exit status 82
panic: exit status 82

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7fff5c098b90, 0x9, 0x7fff5c098ba2, 0x18, 0x7fff5c098b59, 0x2f, 0xc0000df5e0, 0x1, 0x1, 0xc0001e20a0, ...)
        /home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:122 +0x5b4
github.com/brentp/smoove/lumpy.Main()
        /home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:320 +0x25f
main.main()
        /home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:123 +0x1d7
```


It's weird since I can manually execute the lumpy_filter commands and not get errors. 
In case it helps I'm running smoove on RHEL 7.5 and using Anaconda python 3.6.

**Comment by dfermin** [comment]
No dice there. I get the same exit 82 error. 
I tried: `export TMPDIR=/scratch/tmp` which is a physical disk on the server that isn't backed up.

**Comment by brentp** [comment]
that is odd. we can see from the message that lumpy filter has finished (sucessfully) but the exit code is 82.
so it's not the lumpy_filter command, it's the move or the copy. Do you have sufficient drive space available in those locations?

**Comment by dfermin** [comment]
Yes, I have ~10TB in that mount point. I'm only running it on one sample and the BAM file is 8GB. The drive space is backed up. Do you think I should move the entire process to `/scratch/tmp` to try it out?

**Comment by brentp** [comment]
yes. that's all I can think of.

**Comment by dfermin** [comment]
Unfortunately that didn't work either. I tried moving the BAM file and FASTA file to `/scratch/tmp` and running commands there. I then tried recreating the Anaconda environment and using Python 2.7 instead of Python 3.6.  I then tried a different FASTA file but still get the same error. Not sure what it's about.

**Comment by brentp** [comment]
I can't think of much else. Is there anything else different about your file system?
What does `bash -c 'echo $BASH_VERSION' ` show? Maybe there's something odd about your bash?
and what does `echo $SHELL` show?

**Comment by dfermin** [comment]
Yeah I don't have a clue what's going on.
`bash -c 'echo $BASH_VERSION' ` returns `4.2.46(2)-release`
`echo $SHELL` returns `/bin/bash`

The directory I'm in an NFS mount. It has > 10TB of space available. I don't think it's the drive though since the local `/scratch/tmp` directory also gave errors (that's ext4). 

I verified that lumpy_filter does run without issues just not through smoove which is really bizarre .

**Comment by dfermin** [comment]
In case it helps I've copied the BAM files and FASTA files over to a complete separate machine and placed the files in a local drive there.

I installed smoove and it's dependencies:
```
smoove

smoove version: 0.2.3

smoove calls several programs. Those with 'Y' are found on your $PATH. Only those with '*' are required.

 *[Y] bgzip [ sort   -> (compress) ->   index ]
 *[Y] gsort [(sort)  ->  compress   ->  index ]
 *[Y] tabix [ sort   ->  compress   -> (index)]
 *[Y] lumpy
 *[Y] lumpy_filter
 *[Y] samtools
 *[Y] svtyper
 *[Y] mosdepth [extra filtering of split and discordant files for better scaling]

  [Y] duphold [(optional) annotate calls with depth changes]
  [Y] svtools [only needed for large cohorts].

Available sub-commands are below. Each can be run with -h for additional help.
```
And I ran the command again:

```
smoove call --outdir ./data/calls --name samp_031.chr11 --fasta ./data/hs37d5.fa ./bam.files/samp_031.chr11.bam

```

I get the same error message on this machine:
```
(smoove) [dfermin@RhondaB smoove]$ smoove call --outdir ./data/calls --name samp_031 --fasta ./data/hs37d5.fa -p 1 ./bam.files/samp_031.chr11.bam
[smoove] 2019/01/11 14:18:19 starting with version 0.2.3
[smoove] 2019/01/11 14:18:19 calculating bam stats for 1 bams
[smoove] 2019/01/11 14:18:43 done calculating bam stats
[smoove]: ([E]lumpy-filter) 2019/01/11 14:18:53 [lumpy_filter] extracted splits and discordants from 29274188 total aligned reads
[smoove]:2019/01/11 14:18:53 finished process: lumpy-filter (set -eu; lumpy_filter -f ./data/hs37d5.fa ./bam.files/samp_031.chr11.bam ./dat) in user-time:1m26.516847s system-time:4.766275s
[smoove]:2019/01/11 14:18:53 error running command: set -eu; lumpy_filter -f ./data/hs37d5.fa ./bam.files/samp_031.chr11.bam ./data/calls/samp_031.split.bam.tmp.bam ./data/calls/samp_031.disc.bam.tmp.bam 2 && mv ./data/calls/samp_031.split.bam.tmp.bam ./data/calls/samp_031.split.bam && mv ./data/calls/samp_031.disc.bam.tmp.bam ./data/calls/samp_031.disc.bam && cp ./data/calls/samp_031.split.bam ./data/calls/samp_031.split.bam.orig.bam && cp ./data/calls/samp_031.disc.bam ./data/calls/samp_031.disc.bam.orig.bam -> exit status 82
panic: exit status 82

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7ffc5489f331, 0x9, 0x7ffc5489f343, 0x25, 0x7ffc5489f31d, 0xc, 0xc000174640, 0x1, 0x1, 0xc0000b9180, ...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:127 +0x5c9
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:334 +0x277
main.main()
	/home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1d7
```
This time the bash shell is version 4.1.2(1)-release.  All the files are local to a physical disk on this machine that is formatted as ext4 and has > 200GB of space available to me. The OS is RHEL 6.1.  Python is 2.7

I've verified that lumpy_filter will run to completion on it's own so I'm totally lost as to why this isn't working.

**Comment by dfermin** [comment]
Is this line a point of concern?
```
[smoove]:2019/01/11 14:18:53 finished process: lumpy-filter (set -eu; lumpy_filter -f ./data/hs37d5.fa ./bam.files/samp_031.chr11.bam ./dat)
``` 
It might be just truncated information but it _looks like_ it's trying to write to `./dat` which doesn't exist.

**Comment by brentp** [comment]
@dfermin sorry for the delay, and the trouble this was an odd bug. It's fixed in lumpy_filter here: https://github.com/arq5x/lumpy-sv/pull/300/files
once that is merged, you can update your lumpy_filter and all should be ok.
