### ISSUE TITLE
Error in lumpy-filter

### ISSUE THREAD

**Issue by Martaprf** [brentp/smoove#191]
Helllo,

I have been using smoove for a while, but now I got a error message that I do not understand:
```
[smoove]: ([E]lumpy-filter) 2022/03/10 13:28:03 [lumpy_filter] extracted splits and discordants from 596720214 total aligned reads
[smoove]:2022/03/10 13:28:08 finished process: lumpy-filter (set -eu; lumpy_filter -f /home/mferreira/WGS_RM/reference_genome/Homo_sapiens.GRCh38.dna_sm.primary_) in user-time:30m8.25846s system-time:1m54.642271s
[smoove]:([E]lumpy-filter) 2022/03/10 13:28:49 [lumpy_filter] extracted splits and discordants from 590530375 total aligned reads
[smoove]:([E]lumpy-filter) 2022/03/10 13:28:49 mv: cannot stat 'teste/SAMPLE1.split.bam.tmp.bam'
[smoove]:([E]lumpy-filter) 2022/03/10 13:28:49 : No such file or directory
[smoove]:2022/03/10 13:28:49 finished process: lumpy-filter (set -eu; lumpy_filter -f /home/mferreira/WGS_RM/reference_genome/Homo_sapiens.GRCh38.dna_sm.primary_) in user-time:27m58.363001s system-time:1m43.333499s
[smoove]:2022/03/10 13:28:49 error running command: set -eu; lumpy_filter -f /home/mferreira/WGS_RM/reference_genome/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa /home/mferreira/WGS_RM/alignments/post_processed/others/11.postprocessed.bam teste/SAMPLE1.split.bam.tmp.bam teste/SAMPLE1.disc.bam.tmp.bam 2 && mv teste/SAMPLE1.split.bam.tmp.bam teste/SAMPLE1.split.bam && mv teste/SAMPLE1.disc.bam.tmp.bam teste/SAMPLE1.disc.bam && cp teste/SAMPLE1.split.bam teste/SAMPLE1.split.bam.orig.bam && cp teste/SAMPLE1.disc.bam teste/SAMPLE1.disc.bam.orig.bam -> exit status 1
```

My command line is :
`/home/mferreira/programs/smoove-0.2.8/smoove call -x --name sample_10 --fasta  /home/mferreira/WGS_RM/reference_genome/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa -p 10 --outdir teste --genotype /home/mferreira/WGS_RM/alignments/post_processed/others/10.postprocessed.bam`

Someone can help me to understand what I am made wrong?

Thanks
Marta

**Comment by brentp** [comment]
Hi, were you processing another sample at the same time that also had the sample name of `SAMPLE1` ? could you remove the `teste` directory and start the process again?

**Comment by Martaprf** [comment]
Hi,

Yes I am trying with two samples at the same time, but they don´t have the name of SAMPLE1, maybe I need some argument two put the samples names!!!!

**Comment by brentp** [comment]
can you show the read-groups from both the bams that you are running at once?

**Comment by Martaprf** [comment]
Ok, I allredy see the problem, my read-groups have the same SM for the two samples, so maybe I need put there the id of samples?

`
#samtools view -H 10.postprocessed.bam | grep @RG
@RG     ID:10   SM:SAMPLE1      PL:ILLUMINA     LB:10.ATGAGGCC+CAATTAAC PU:HTGNKDSXY.2
 samtools view -H 11.postprocessed.bam | grep @RG
@RG     ID:11   SM:SAMPLE1      PL:ILLUMINA     LB:11.ACTAAGAT+CCGCGGTT PU:HTGNKDSXY.2
`

Thanks a lot for the help!

**Comment by brentp** [comment]
Great. Thanks for following up.
