### ISSUE TITLE
libcrypto.so.1.0.0: cannot open shared object file error with biocontainers

### ISSUE THREAD

**Issue by georgiesamaha** [brentp/smoove#193]
Hi, 

Like previous users (#173, #147, #102, #13) I've run into the cannot find/open libcrypto error, this time while using Singularity and biocontainers (docker://quay.io/biocontainers/smoove:0.2.8--h9ee0642_0 and docker://quay.io/biocontainers/smoove:0.2.7--h9ee0642_0). I attempted to resolve the issue using the workarounds similar to that suggested by #173, but wasn't successful. Running both containers on two different systems I get the following error: 

```
[smoove] 2022/03/21 05:23:16 starting with version 0.2.8
[smoove] 2022/03/21 05:23:16 calculating bam stats for 1 bams
[smoove]: ([E]lumpy-filter) 2022/03/21 05:23:16 lumpy_filter: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

Cheers,
Georgie

**Comment by brentp** [comment]
Hi, you can try, e.g.:
```
conda config --add channels bioconda
conda config --add channels conda-forge
conda install samtools==1.12
```

**Comment by georgiesamaha** [comment]
Hi Brent,

Thanks for getting back to me. 

We are developing a portable structural variant calling pipeline with Singularity, biocontainers and nextflow. We were hoping to include Smoove as one of the tools. We hadn't planned to use conda. Is there another container source you recommend?

**Comment by brentp** [comment]
Hi, I do not maintain the biocontainers image. The docker image brentp/smoove should work find though.

**Comment by georgiesamaha** [comment]
ok thanks for your help

**Comment by microtan0902** [comment]
> Hi, you can try, e.g.:
> 
> ```
> conda config --add channels bioconda
> conda config --add channels conda-forge
> conda install samtools==1.12
> ```

If so, the following packages (especially for lumpy-sv) will be DOWNGRADED:

  duphold                                  0.2.1-hec16e2b_3 --> 0.1.4-0
  libdeflate                                1.10-h7f98852_0 --> 1.7-h7f98852_5
  lumpy-sv                                 0.3.0-ha52163a_3 --> 0.2.14a-hdfb72b2_2
  pysam                               0.19.0-py27hc2126ed_0 --> 0.17.0-py27hc729bab_0

**Comment by rpetit3** [comment]
@brentp I'll update the bioconda package (might just need a rebuild). Do you by chance any recommended pinnings, or should latest be fine?

**Comment by brentp** [comment]
I don't think there's any need to pin, but you could set to the latest versions.
Thank you for debugging this!

**Comment by rpetit3** [comment]
No problem! If you don't hear from me, consider all is well! Thanks for writing smoove.

Cheers

**Comment by rpetit3** [comment]
@georgiesamaha should now be fixed on Biocontainer `quay.io/biocontainers/smoove:0.2.8--h9ee0642_1`

@brentp thanks as always, ended up having to pin `lumpy-sv >=0.3`
