### ISSUE TITLE
important_regions bed

### ISSUE THREAD

**Issue by skose82** [brentp/smoove#203]
Hi there,

I have a few questions running smoove/Lumpy for the first time. 

1. For the following command in samplot vcf: 

samplot vcf --filter "SVTYPE == 'DEL' & SU >= 8" --filter "SVTYPE == 'INV' & SU >= 5" --vcf example.vcf -d test -O png --important_regions regions.bed -b sample1.bam sample2.bam sample3.bam > samplot_commands.sh

Is the important regions bed required? Is this the same as the exclude bed file found here: 
https://github.com/hall-lab/speedseq/blob/master/annotations/exclude.cnvnator_100bp.GRCh38.20170403.bed

2. If not is there a recommended bed file to use for this? 

3. Is there any further information as to why SU is set to >= 8 and INV >= 5?

Many thanks

**Comment by brentp** [comment]
Hi, it seems this is more of a question for samplot. I don't think the --important_regions is required. You likely don't want to use the exclude file for that argument.
I don't know where you got this example command, but it might be just an example.
hope that helps.
-B

**Comment by skose82** [comment]
Much appreciated will check with samplot devs.
