### ISSUE TITLE
Question about Exclude region 

### ISSUE THREAD

**Issue by hayeon-pak** [brentp/smoove#206]
Hi :)

I tried to use smoove. And my code is below

`smoove call  --name $sample_id  --exclude dir/to/ceph18.b37.lumpy.exclude.2014-01-15.bed  --fasta $ref_hg19_fa  --outdir $out_path  --genotype  --duphold -p 1 $in_bam_file`

But, when I got result, some variant contained 'exclude region'

For example,
in ceph18.b37.lumpy.exclude.2014-01-15.bed
`1	70027377	70027675`

`4	49633314	52668449`

and one of my result

`chr1    70027324        4367    N       <DEL>   1085.3  . SVTYPE=DEL;SVLEN=-352;END=70027676;STRANDS=+-:38;IMPRECISE;CIPOS=-21,92;CIEND=-108,29;CIPOS95=-2,27;CIEND95=-31,5;SU=38;PE=38;SR=0;PRPOS=3.28842e-14,1.48926e-13,6.7368e-13,3.04501e-12,1.37487e-11,6.2025 ........................... 22,1.80397e-24,2.59285e-26,3.71925e-28,2.88433e-30,1.64223e-32,9.33575e-35,5.30169e-37,3.00445e-39,1.70081e-41,9.61207e-44;AC=1;AN=2;GCF=0.507082;MSHQ=4     GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB:DHFC:DHFFC:DHBFC:DHSP:SHQ 0/1:125:1085.34:-110,-1,-14:80:35:45:34:44:6:0:6:28:38:0.56:0.25:0.232877:0.283333:39:4`

`chr4    49634039        55109   N       <DEL>   16470.1 .       SVTYPE=DEL;SVLEN=-23809;END=49657848;STRANDS=+-:4;IMPRECISE;CIPOS=-30,449;CIEND=-450,29;CIPOS95=0,257;CIEND95=-257,0;SU=4;PE=4;SR=0;PRPOS=3.89606e-19,1.33033e-18,4.54247e-18,1.55105e-17,5.29613e-17,1.80839e-16,6.17484e-16,2.10843e-15,7.19933e-15,2.45825e-14,8.39381e-14,2.86611e-13,9.78646e-13,3.34163e-12,1.14102e-11,3.89606e-11,1.330 ......................... 63,9.78646e-05,2.86611e-05,8.39381e-06,2.45825e-06,7.19933e-07,2.10843e-07,6.17484e-08,1.80839e-08,5.29613e-09,1.55105e-09,4.54247e-10,1.33033e-10,3.89606e-11,1.14102e-11,3.34163e-12,9.78646e-13,2.86611e-13,8.39381e-14,2.45825e-14,7.19933e-15,2.10843e-15,6.17484e-16,1.80839e-16,5.29613e-17,1.55105e-17,4.54247e-18,1.33033e-18;AC=1;AN=2;GCF=0.407644;MSHQ=4      GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB:DHFC:DHFFC:DHBFC:DHSP:SHQ      0/1:200:16470.1:-1674,-27,-688:1968:1220:747:1219:746:865:4:722:354:20:0.38:4.94366:1.57399:4.875:25:4`

I don't know why I get this result.
Help me 

Thank you!

**Comment by brentp** [comment]
Hi, your exclude regions are e.g. chromosome "1" whereas your Bam file has "chr1", if you add the chr prefix to the exclude, then it will work.

**Comment by hayeon-pak** [comment]
Thanks your reply :)

Can I know how many base of exclude region have to overlap with my variant call? 
Because I chaged exclude chr prefix (1 -> chr 1), but still remain some call on exclude region.

**Comment by brentp** [comment]
I suspect any remaining calls have reads that overlap the boundary. Smoove does not report the amount of overlap.
