### ISSUE TITLE
runtime: failed to create new OS thread

### ISSUE THREAD

**Issue by asylvz** [brentp/smoove#207]
Hello,

I'm running smoke on docker and get the following error. Do you have any suggestion?

Thank you,
Arda

docker run -v /Users/asoylev/genomes:/inp -it brentp/smoove smoove call -name dnm --fasta /inp/hg38.fasta --genotype /inp/hg00733_grch38_realigned.bam
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[smoove] 2022/10/24 21:36:09 starting with version 0.2.6
[smoove] 2022/10/24 21:36:09 calculating bam stats for 1 bams
[smoove] 2022/10/24 21:36:40 done calculating bam stats

[smoove]: ([E]lumpy-filter) 2022/10/24 22:19:14 [lumpy_filter] extracted splits and discordants from 696974278 total aligned reads
[smoove]:2022/10/24 22:19:17 finished process: lumpy-filter (set -eu; lumpy_filter -f /inp/hg38.fasta /inp/hg00733_grch38_realigned.bam .//sample.split.bam.tmp.b) in user-time:56m8.612767s system-time:15m5.577029s

[smoove] 2022/10/24 22:24:19 removed 5858450 alignments out of 7295943 (80.30%) with low mapq, depth > 1000, or from excluded chroms from sample.split.bam in 303 seconds
[smoove] 2022/10/24 22:24:19 removed 388849 alignments out of 7295943 (5.33%) that were bad interchromosomals or flanked-splitters from sample.split.bam

[smoove] 2022/10/24 22:28:50 removed 10477804 alignments out of 15968796 (65.61%) with low mapq, depth > 1000, or from excluded chroms from sample.disc.bam in 573 seconds
[smoove] 2022/10/24 22:28:50 removed 452679 alignments out of 15968796 (2.83%) that were bad interchromosomals or flanked-splitters from sample.disc.bam

[smoove] 2022/10/24 22:36:01 kept 9248 putative orphans
[smoove] 2022/10/24 22:36:01 removed 1228327 discordant orphans in 306 seconds
[smoove] 2022/10/24 22:36:57 removed 4738501 singletons and isolated interchromosomals of 5038313 reads (94.05%) from sample.disc.bam in 488 seconds
[smoove] 2022/10/24 22:36:57 299812 reads (1.88%) of the original 15968796 remain from sample.disc.bam

[smoove] 2022/10/24 22:37:48 kept 100685 putative orphans
[smoove] 2022/10/24 22:37:48 removed 172600 split orphans in 704 seconds
[smoove] 2022/10/24 22:38:04 removed 661586 singletons of 1048644 reads (63.09%) from sample.split.bam in 824 seconds
[smoove] 2022/10/24 22:38:04 387058 reads (5.31%) of the original 7295943 remain from sample.split.bam
[smoove] 2022/10/24 22:38:04 starting lumpy
[smoove] 2022/10/24 22:38:04 wrote lumpy command to .//dnm-lumpy-cmd.sh
[smoove] 2022/10/24 22:38:04 writing sorted, indexed file to dnm-smoove.genotyped.vcf.gz
[smoove] 2022/10/24 22:38:04 excluding variants with all unknown or homozygous reference genotypes
[smoove] 2022/10/24 22:38:05 runtime: failed to create new OS thread (have 2
[smoove] 2022/10/24 22:38:05  already; errno=22)
fatal error: newosproc
[smoove] 2022/10/24 22:38:05 
runtime stack:
[smoove] 2022/10/24 22:38:05 runtime.throw(
[smoove] 2022/10/24 22:38:05 0x6cb13d
[smoove] 2022/10/24 22:38:05 , 
[smoove] 2022/10/24 22:38:05 0x9)
[smoove] 2022/10/24 22:38:05 	/home/brentp/go/go1.8/src/runtime/panic.go:596 +0x95
runtime.newosproc(0xc420024000, 0xc420034000)
	/home/brentp/go/go1.8/src/runtime/os_linux.go:163 +0x18c
runtime.newm(0x6d9d28, 0x0)
	/home/brentp/go/go1.8/src/runtime/proc.go:1628 +0x137
runtime.main.func1()
	/home/brentp/go/go1.8/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x815400)
	
[smoove] 2022/10/24 22:38:05 /home/brentp/go/go1.8/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
	/home/brentp/go/go1.8/src/runtime/proc.go:1132

goroutine 1 [running]:
[smoove] 2022/10/24 22:38:05 runtime.systemstack_switch()
	/home/brentp/go/go1.8/src/runtime/asm_amd64.s:281 fp=0xc420020788 sp=
[smoove] 2022/10/24 22:38:05 0xc420020780
runtime.main()
	/home/brentp/go/go1.8/src/runtime/proc.go:127 +0x6c fp=0xc4200207e0 sp=0xc420020788
[smoove] 2022/10/24 22:38:05 runtime.goexit()
	/home/brentp/go/go1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4200207e8 sp=0xc4200207e0
[smoove] 2022/10/24 22:38:05 Failed to read from standard input: unknown file type
[smoove] 2022/10/24 22:38:05 chr1	1000000
[smoove] 2022/10/24 22:38:05 [W::hts_idx_load3] 
[smoove] 2022/10/24 22:38:05 The index file is older than the data file: /inp/hg00733_grch38_realigned.bai
[smoove] 2022/10/24 22:38:05 
[smoove] 2022/10/24 22:38:37 chr10	1000000
[smoove] 2022/10/24 22:38:55 chr11	1000000
[smoove] 2022/10/24 22:38:59 [W::hts_idx_load3] The index file is older than the data file: /inp/hg00733_grch38_realigned.bai
[smoove] 2022/10/24 22:38:59 
[smoove] 2022/10/24 22:39:11 chr12	1000000
[smoove] 2022/10/24 22:39:29 chr13	1000000
[smoove] 2022/10/24 22:39:29 chr13	2000000
chr13	4000000
chr13	8000000
chr13	16000000
chr13	32000000
[smoove] 2022/10/24 22:39:41 chr14	1000000
chr14	2000000
chr14	4000000
chr14	8000000
chr14	16000000
[smoove] 2022/10/24 22:39:41 chr14	32000000
[smoove] 2022/10/24 22:39:46 [W::hts_idx_load3] 
[smoove] 2022/10/24 22:39:46 The index file is older than the data file: /inp/hg00733_grch38_realigned.bai
[smoove] 2022/10/24 22:39:46 
[smoove] 2022/10/24 22:39:52 chr14_GL000009v2_random	1000000
[smoove] 2022/10/24 22:39:52 chr14_GL000225v1_random	1000000
[smoove] 2022/10/24 22:39:52 chr14_KI270722v1_random	1000000
[smoove] 2022/10/24 22:39:52 chr14_GL000194v1_random	1000000
[smoove] 2022/10/24 22:39:52 chr14_KI270723v1_random	1000000
[smoove] 2022/10/24 22:39:52 chr14_KI270724v1_random	1000000
[smoove] 2022/10/24 22:39:52 chr14_KI270725v1_random	1000000
[smoove] 2022/10/24 22:39:52 chr14_KI270726v1_random	1000000
[smoove] 2022/10/24 22:39:53 chr15	1000000
chr15	2000000
chr15	4000000
[smoove] 2022/10/24 22:39:53 chr15	8000000
chr15	16000000
chr15	32000000
[smoove] 2022/10/24 22:40:03 chr16	1000000
[smoove] 2022/10/24 22:40:17 chr16_KI270728v1_random	1000000
[smoove] 2022/10/24 22:40:17 chr17	1000000
[smoove] 2022/10/24 22:40:30 chr17_GL000205v2_random	1000000
[smoove] 2022/10/24 22:40:30 chr17_KI270729v1_random	1000000
panic: write |1: broken pipe

goroutine 117394 [running]:
github.com/brentp/smoove/svtyper.check(...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper.func2(0xc000a826c0, 0xc000148590, 0x1, 0x1, 0x4000800ea8, 0xf, 0xc000a90300, 0x2c, 0xc0044eae18, 0xc0044eae30, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:189 +0x8e7
created by github.com/brentp/smoove/svtyper.Svtyper
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:165 +0xab2

**Comment by brentp** [comment]
Hi, I think this is likely the problem:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
you're running on arm64?

**Comment by brentp** [comment]
I'm surprised it got this far. You could try `export GOMAXPROCS=1` before running. And also run with `-p 1`
Or can you give it somehow access to more processes as that's what the final error is indicating.

**Comment by asylvz** [comment]
Thank you, I'll try to check that but it took hours to get to that point. I just tried with a linux machine and it was extremely fast compared to that.
