### ISSUE TITLE
[smoove] 2022/11/15 10:20:53 starting with version 0.2.8 [smoove] 2022/11/15 10:20:53 lumpy executable not found in PATH

### ISSUE THREAD

**Issue by assane-mbodj** [brentp/smoove#209]

**Comment by assane-mbodj** [comment]
I @brentp
I want to run smoove call on my illumina data but I had this error ?
[smoove] 2022/11/15 10:20:53 starting with version 0.2.8
[smoove] 2022/11/15 10:20:53 lumpy executable not found in PATH

Please May i help me to resolve this problem
Thank in advance

**Comment by brentp** [comment]
Hi, you'll need to install all the required programs to run smoove. If you run smoove without any arguments, it will show which it can find. You can also install from conda (bioconda) which will handle this.
