### ISSUE TITLE
 samtools index: failed to create index for *mybamfile*  panic: exit status 1

### ISSUE THREAD

**Issue by framic23** [brentp/smoove#212]
Hi, while running smoove this error occurs. 
` WARNING: underlay of /usr/share/zoneinfo/Etc/UTC required more than 50 (81) bind mounts
  [smoove] 2022/12/14 01:18:54 starting with version 0.2.6
  [smoove] 2022/12/14 01:18:54 calculating bam stats for 1 bams
  [smoove] 2022/12/14 01:20:03 done calculating bam stats
  [smoove]: ([E]lumpy-filter) 2022/12/14 03:01:44 [lumpy_filter] extracted splits and discordants from 780902882 total aligned reads
  [smoove]:2022/12/14 03:02:07 finished process: lumpy-filter (set -eu; lumpy_filter -f GRCh38.d1.vd1.fa sorted_DNA.bam .//sorted_DNA.split.bam.tm) in user-time:1h34m1.018034s system-time:13m56.817703s
  [E::hts_idx_push] Chromosome blocks not continuous
  [E::sam_index] Read 'V300042162L2C001R0010000456' with ref_name='chr4', ref_length=190214555, flags=97, pos=85001647 cannot be indexed
  samtools index: failed to create index for "./sorted_DNA.disc.bam"
  panic: exit status 1
  `
The BAM input file is sorted by name and not by coordinate. Could be this the problem causing this error? Should I run smoove without previous sorting the file?

**Comment by brentp** [comment]
Hi, Yes, the bam must be sorted by coordinate and indexed.
