### ISSUE TITLE
No INS records

### ISSUE THREAD

**Issue by zhixue** [brentp/smoove#216]
Thank you for your awesome tool for calling and genotyping SVs! 
It is really smooth and user-friendly!

I had problems about the insertion records in results. 
I tested two real data sets to call SVs with commands:
```shell
sample=SampleA # or sampleB

# bwa map
echo "# BWA map"
bwa mem -t 8 -M ~/ref/Chr.fa ${sample}_1.fq.gz ${sample}_2.fq.gz > ${sample}.sam 2> ./${sample}.mem-pe.log

# samtools sort index
samtools sort -o ${sample}.bam ${sample}.sam
samtools index ${sample}.bam
rm -rf ${sample}.sam

# smoove 0.2.8, call SVs
singularity exec ~/tools/smoove_latest.sif smoove call --outdir ${sample}_smoove --name $sample --fasta ~/ref/Chr.fa -p 1 --genotype ${sample}.bam

# count ins records
cat ${sample}_smoove/${sample}-smoove.genotyped.vcf.gz| grep 'SVTYPE=INS'|wc -l
# 0

# check ins in annotation lines
cat ${sample}_smoove/${sample}-smoove.genotyped.vcf.gz| grep 'INS'
# ##ALT=<ID=INS,Description="Insertion of novel sequence">
```
but I got no INS records in both of two data sets.

Files could be downloaded here:
[SampleA-smoove.genotyped.vcf.gz](https://cgm.sjtu.edu.cn/test/hzxue/SampleA-smoove.genotyped.vcf.gz) and [SampleB-smoove.genotyped.vcf.gz](https://cgm.sjtu.edu.cn/test/hzxue/SampleB-smoove.genotyped.vcf.gz).

I noticed that ''excluding variants with all unknown or homozygous reference genotypes'' existed in log. So INS is defined as unknown? Is it correct?

**Comment by brentp** [comment]
Hi, 
Smoove uses lumpy and svtyper which do not handle insertions. So we don't expect any in the output.
