### ISSUE TITLE
fasta files input error

### ISSUE THREAD

**Issue by zlye** [brentp/smoove#22]
Hi
- I am guessing this error is somewhat trivial but I can't seem to work it out, I am running smoove call and getting and error "panic: no fai for fasta"  during the "writing sorted, indexed file to..." stage.

I've checked to see if there is a labeling difference in the genome file prefix and bam file - I see that gsort "will error if your genome file has 'chr' prefix and your file does not (or vice-versa)" - and I don't think this is the issue, could you explain what this means in more detail? Any other suggestions?
Thanks

**Comment by brentp** [comment]
Hi Zoe, can you show how you ran smoove and the full output that it showed along with the contents of the directory containing the fasta?

**Comment by zlye** [comment]
Hi Brent,
Here is the command and output, I am running singularity on my
institution's computing cluster. - installed by the administrator. Thanks
again for your help I really appreciate it!

*command:*

/share/apps/singularity/bin/singularity exec
/beegfs/work/public/singularity/smoove-0.1.6.simg
smoove call\

        --outdir <path to out directory>\

        --name <sampleID>\

        --fasta <pathtovasta> -p 1\

        --genotype <samplepath><sampleid>.dedup.bam *(combination of
variable gives complete BAM file path)*


*output:*

[smoove] 2018/08/24 09:58:26 starting with version 0.1.6

[smoove] 2018/08/24 09:58:27 calculating bam stats for 1 bams

[smoove] 2018/08/24 09:58:29 done calculating bam stats

[smoove] 2018/08/24 09:58:36 removed 0 alignments out of 150922 (0.00%)
with depth > 800 or from excluded chroms from IRGC_10430.disc.bam in 8
seconds

[smoove] 2018/08/24 09:58:36 removed 0 alignments out of 150922 (0.00%)
that were bad interchromosomals or flanked-splitters from
IRGC_10430.disc.bam

[smoove] 2018/08/24 09:58:39 removed 0 singletons out of 150922 reads
(0.00%) from IRGC_10430.disc.bam in 2 seconds

[smoove] 2018/08/24 09:58:42 removed 0 alignments out of 634 (0.00%) with
depth > 800 or from excluded chroms from IRGC_10430.split.bam in 3 seconds

[smoove] 2018/08/24 09:58:42 removed 0 alignments out of 634 (0.00%) that
were bad interchromosomals or flanked-splitters from IRGC_10430.split.bam

[smoove] 2018/08/24 09:58:42 removed 0 singletons out of 634 reads (0.00%)
from IRGC_10430.split.bam in 0 seconds

[smoove] 2018/08/24 09:58:42 starting lumpy

[smoove] 2018/08/24 09:58:42 wrote lumpy command to
/scratch/znl207/smoove/testing//IRGC_10430-lumpy-cmd.sh

[smoove] 2018/08/24 09:58:42 writing sorted, indexed file to
/scratch/znl207/smoove/testing/IRGC_10430-smoove.genotyped.vcf.gz

[smoove] 2018/08/24 09:58:42 excluding variants with all unknown or
homozygous reference genotypes

[smoove] 2018/08/24 09:58:43 > gsort version 0.0.6

[smoove] 2018/08/24 09:58:43 422

[smoove] 2018/08/24 09:58:43

[smoove] 2018/08/24 09:58:43 0

[smoove] 2018/08/24 09:58:43

panic: no fai for fasta


goroutine 5878 [running]:

github.com/brentp/smoove/lumpy.check(0x9f97c0, 0xc42005ce00)

/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:50 +0x4a

github.com/brentp/smoove/lumpy.writeContigs(0xc42006e240, 0x7fffbce19d98,
0x50)

/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:202 +0x72

github.com/brentp/smoove/lumpy.bndFilter.func1(0xc42000e168, 0xc42006e240,
0xc42053c480, 0xc420af0c68, 0x7fffbce19d98, 0x50, 0x6)

/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:229 +0x119

created by github.com/brentp/smoove/lumpy.bndFilter

/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:220 +0x2cb

**Comment by brentp** [comment]
you haven't shown the exact command or the contents of the fasta directory so it's difficult to diagnose, but I'd guess that singularity does not have access to the location where your fasta file is saved.

**Comment by yqlan** [comment]
Got the same error with singularity.

error:

'panic: error opening fasta file: /project2/araman/yqlan/yeastAdaptation_seqData/yeast_reference_genome-genes/sacCer3_WGS_idx/sacCer3.fa: no fai for fasta'

command:

`
genome_idx=/project2/araman/yqlan/yeastAdaptation_seqData/yeast_reference_genome-genes/sacCer3_WGS_idx/sacCer3.fa
smoove_sig=/project2/araman/yqlan/software/smoove.sif
module load singularity/3.4.0
cd /project2/araman/yqlan/yeastAdaptation_seqData/wholeGenomeSeq_results/20240131_LH00315_0080_B22H3W5LT3-AR-Lan-8s

singularity exec $smoove_sig smoove call \
        --outdir ./smoove_output/ \
        --name AR-Lan-8s \
        --fasta $genome_idx \
        --support 100 \
        -p 2 \
        --genotype \
        ./gatk_dataPreprocess/AR-YL-8s-*_recal.bam
`

any ideas? appreciate it.
thanks

**Comment by brentp** [comment]
usually this means you need to bind that directory so that it is available within singularity.
