### ISSUE TITLE
A bug when installing smoove with conda

### ISSUE THREAD

**Issue by Ceonham** [brentp/smoove#232]
Hi Brent, I installed smoove by mamba and performed population calling of more than 200 plant samples.  However, I met the warning messages like: "bash: line 1: 37699 Segmentation fault (core dumped)" which appears to happen in the old versions of lumpy due to the existence of scaffolds in the reference genome. I directly ran lumpy and found the version is 0.2.13. Then I tried to update lumpy using "mamba install -c bioconda lumpy-sv=0.3.1" and "conda install -c bioconda lumpy-sv=0.3.1". At the pre-installation stage, the lumpy version in the package list is 0.3.1 but after the installation, the version came back to 0.2.13. I wonder if it is a bug of conda and do you have suggestions to fix this? Looking forward to your reply. Thank you so much!!!
![图片](https://github.com/brentp/smoove/assets/75994304/cf492dab-1591-4ea7-b34a-405460fdd218)
![图片](https://github.com/brentp/smoove/assets/75994304/96d95f3d-7b23-4c7a-bef3-223a947c8fa4)

**Comment by brentp** [comment]
the [recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/smoove/meta.yaml#L23) in conda require lumpy > 0.3, so it's not the conda/mamba, it's something else.
I would use `which lumpy` to make sure your PATH has the mamba lumpy first.

**Comment by Ceonham** [comment]
Thank you for reminding. I created a new environment "smoove" to install it again in another server and got the same problem. The installed lumpy is indeed the old version and I'm sure it is in my mamba path. Meanwhile, I found the date of lumpy is different from the system but svtyper and svtools are same. Please check the attached screenshots. Thank you!!!

Ceonham


---------------- 

----------原邮件信息----------
发件人："Brent Pedersen" ***@***.***>
收件人："brentp/smoove" ***@***.***>
抄送人："Ceonham" ***@***.***>, "Author" ***@***.***>
主题：Re: [brentp/smoove] A bug when installing smoove with conda (Issue#232)
发送时间：2023-10-11 20:13:30

 the [recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/smoove/meta.yaml#L23) in conda require lumpy > 0.3, so it's not the conda/mamba, it's something else.
I would use `which lumpy` to make sure your PATH has the mamba lumpy first.

**Comment by Ceonham** [comment]
Hi Brent, I just tried to install it with docker and found the lumpy version is also 0.2.13! Please check the screenshot again. Many thanks!
Ceonham


---------------- 

----------原邮件信息----------
发件人："秦晗" ***@***.***>
收件人："brentp/smoove" ***@***.***>, "brentp/smoove" ***@***.***>
抄送人："Author" ***@***.***>
主题：Re:Re: [brentp/smoove] A bug when installing smoove with conda (Issue#232)
发送时间：2023-10-11 21:00:42

 Thank you for reminding. I created a new environment "smoove" to install it again in another server and got the same problem. The installed lumpy is indeed the old version and I'm sure it is in my mamba path. Meanwhile, I found the date of lumpy is different from the system but svtyper and svtools are same. Please check the attached screenshots. Thank you!!!

Ceonham


----------------

----------原邮件信息----------
发件人："Brent Pedersen" ***@***.***>
收件人："brentp/smoove" ***@***.***>
抄送人："Ceonham" ***@***.***>, "Author" ***@***.***>
主题：Re: [brentp/smoove] A bug when installing smoove with conda (Issue#232)
发送时间：2023-10-11 20:13:30

the [recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/smoove/meta.yaml#L23) in conda require lumpy > 0.3, so it's not the conda/mamba, it's something else.
I would use `which lumpy` to make sure your PATH has the mamba lumpy first.

**Comment by brentp** [comment]
looks like lumpy might not update the version string, but you also need to check that your system is finding the write lumpy.
