### ISSUE TITLE
svtyper: error: unrecognized arguments: --max_ci_dist 0 error

### ISSUE THREAD

**Issue by shaghayeghsoudi** [brentp/smoove#238]
Hi,
I ran into a a couple of new issues when trying to run smoove.
I installed smoove through conda and ended up having `svtyper 0.1.4 `. However when I run the following command 
`smoove call -o ${OUT_DIR} --exclude ${BED} --name ${SAMPLE_ID} --fasta ${FASTA} -p 10 --genotype ${INPUT_DIR}/${SAMPLE_ID}.rmdup1.RG.bam `

I keep getting the error:

`svtyper: error: unrecognized arguments: --max_ci_dist 0`

This is all of the flags I have when I run svtyper:
```
$svtyper
usage: svtyper [-h] [-i FILE] [-o FILE] -B FILE [-T FILE] [-l FILE] [-m INT]
               [-n INT] [-q] [--max_reads INT] [--split_weight FLOAT]
               [--disc_weight FLOAT] [-w FILE]
svtyper: error: argument -B/--bam is required
```

So it seems there is no `--max_ci_dist` argument.

When I exclude the `svtyper` from the smoove call **without** `--genotype` flag I get the output vcfs. However the weird thing is that I get no insertion in the vcf files in my samples. 
Can you please help me to sort out this issue to be able to proceed with my analysis? no insertion in the vcf can be due to the fact that I exclude `--genotype` flag?
Then how can I fix the `svtype` error? I believe I installed the latest version from conda.

Thank you

**Comment by brentp** [comment]
hi, you must have the wrong version of svtyper. You'll have to get a newer version.
And lumpy, which is used by smoove does not call insertions.
