### ISSUE TITLE
export SMOOVE_MAX_DEPTH=20000 doesn't work

### ISSUE THREAD

**Issue by yqlan** [brentp/smoove#242]
command:
`export SMOOVE_MAX_DEPTH=5000`
`smoove call ...`

log file output:
[smoove] 2024/06/14 14:20:10 starting with version 0.2.8
[smoove] 2024/06/14 14:20:11 calculating bam stats for 8 bams
[smoove] 2024/06/14 14:20:43 done calculating bam stats
[smoove] 2024/06/14 14:20:43 couldn't set max depth to 5000

**Comment by brentp** [comment]
oops. the error is in the wrong place. that means it succeeded. I have pushed a fix but you can proceed knowing that it will set the depth as requested.
