### ISSUE TITLE
smoove genotype issue

### ISSUE THREAD

**Issue by Shannan-Summers** [brentp/smoove#247]
smoove] 2024/07/16 13:07:58 starting with version 0.2.8
[smoove] 2024/07/16 13:07:58 writing sorted, indexed file to results-genotyped/sample-joint-smoove.genotyped.vcf.gz
[smoove] 2024/07/16 13:07:58 > gsort version 0.1.4
[smoove] 2024/07/16 13:08:01 Error: failed to build insert size histogram for paired-end reads.
Please ensure BAM file (BU189_B2.disc.bam) has inward facing, paired-end reads.
panic: exit status 1

**Comment by Shannan-Summers** [comment]
this is the code i used 

smoove genotype -d -x -p 1 --name sample-joint --outdir results-genotyped/ --fasta schistosoma_mansoni.PRJEA36577.WBPS18.genomic.fa --vcf merged.sites.vcf.gz *.bam

**Comment by brentp** [comment]
hi, you could run samtools flagstat on the bam with sample id: BU189_B2 and report the results here. Its seems something else is going on. If you have the output from smoove call for that sample, that would also be informative.

**Comment by Shannan-Summers** [comment]
This is the flagstat summary of the original bam file 
samtools flagstat BU189_B2.uniq.sorted.bam
73280785 + 0 in total (QC-passed reads + QC-failed reads)
62648976 + 0 primary
0 + 0 secondary
10631809 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
73280785 + 0 mapped (100.00% : N/A)
62648976 + 0 primary mapped (100.00% : N/A)
62648976 + 0 paired in sequencing
31324488 + 0 read1
31324488 + 0 read2
57904874 + 0 properly paired (92.43% : N/A)
62648976 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
1143674 + 0 with mate mapped to a different chr
522384 + 0 with mate mapped to a different chr (mapQ>=5)


This is the flagstat output. samtools flagstat BU189_B2.disc.bam
2343878 + 0 in total (QC-passed reads + QC-failed reads)
2343878 + 0 primary
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
2343878 + 0 mapped (100.00% : N/A)
2343878 + 0 primary mapped (100.00% : N/A)
2343878 + 0 paired in sequencing
1171939 + 0 read1
1171939 + 0 read2
0 + 0 properly paired (0.00% : N/A)
2343878 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
5962 + 0 with mate mapped to a different chr
5962 + 0 with mate mapped to a different chr (mapQ>=5)

**Comment by brentp** [comment]
so when you do this:
```
smoove genotype -d -x -p 1 --name sample-joint --outdir results-genotyped/ --fasta schistosoma_mansoni.PRJEA36577.WBPS18.genomic.fa --vcf merged.sites.vcf.gz *.bam
```
you should make sure that `*.bam` does not include any .disc.bam files. It should only include the original bam files.

**Comment by Shannan-Summers** [comment]
Thank you!
