### ISSUE TITLE
smoove on tumor-normal pairs

### ISSUE THREAD

**Issue by sbamin** [brentp/smoove#26]
Hi @brentp ,

Thanks for sharing this tool, and indeed makes things easier for using lumpy and related tools. I am using it to call SVs for canine genome. We have tumor-normal pairs on >40 cases. I am thinking of doing joint genotype if in set of 40 bams or so. However, we are primarily interested in somatic SVs and so, I am trying to make a workflow optimized to filter putative somatic SVs from final genotypes vcf. Here is something I can think of:

1. Joint genotype each of tumor-normal pair, and then merge resulting 40 genotyped vcfs to make final vcf with common variants, and then annotate those. Later, I can filter based on genotype in tumor and normal cases, and relevant INFO/FORMAT fields (SHQ, SR, SU, ...??) to identify potential somatic (vs germline) SVs.

or 

2. Joint genotype 40 normals together in first run, and 40 tumors in second run. Instead of merging two merged vcfs, I can intersect these two vcfs and also consider genotype calls in merged normal and tumor vcfs to identify potential somatic vs germline SVs.

or 

3. Alternate workflow design that you may suggest.

Thanks a lot,
Samir

**Comment by brentp** [comment]
Hi Samir, glad to hear it's useful. 

2. is easier, but you might get more false positives.

I would do 1. with `--support 3` to the `smoove call` command. 

For filtering, you can use the new duphold (-d) param when you do the final genotyping to give you an additional piece of information.

**Comment by sbamin** [comment]
Agree and going by 1. schema. Thanks for helpful hints.

**Comment by sbamin** [comment]
Hi Brent,

I followed schema 1 and got paired genotyped vcfs from `smoove call` command. Since I used `--removepr` parameter, `smoove merge` failed with error as it could not find PRPOS flag. I looked into #12, and looks like I needed to exclude `--removepr or -x` parameter if using population-level calling. So, running  `smoove call` again. I am just posting here in case, there is any hidden option to let `smoove merge` work with vcfs without PRPOS flag :-)

```sh
smoove merge --name merged -f ./CanFam3_1.fa --outdir ./smoove/paired_genotyped_calls/*.genotyped.vcf.gz
```

```
[smoove] 2018/10/17 16:08:55 starting with version 0.2.1
[smoove] 2018/10/17 16:08:55 merging 61 files
[smoove] 2018/10/17 16:08:55 finished sorting 61 files; merge starting.
[smoove] 2018/10/17 16:11:01 Required tag PRPOS not found. Please ensure you've run lumpy withthe -P option to emit breakpoint probabilities.
2018/10/17 16:11:01 exit status 1
```

**Comment by brentp** [comment]
aye. smoove merge will not work without the PR stuff.

**Comment by sbamin** [comment]
no worries and already dumped jobs on cluster with no `-x` flag. It's fast and quite reliable for most part, that is what matters more to me. +1 for that.

**Comment by sbamin** [comment]
One more thing: Even though I am using `--excludechroms '~^AA,~^JH'`, somehow I am seeing entries for scaffolds in final vcf. It's ok on my end for now as filtering those out later is trivial.

```
AAEX03025982.1  2571    25806_2 N       [19:13517142[N  557.64  .       SVTYPE=BND;STRANDS=--:23;IMPRECISE;CIPOS=-176,24;CIEND=-132,29;CIPOS95=-41,5;CIEND95=-22,13;MATEID=25806_1;EVENT=25806;SECONDARY;SU=23;PE=23;SR=0;PRPOS=9.35015e-16,1.32318e-15,1.86767e-15,2.64046e-15,...,0.000136868;AC=2;AN=4  GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB   0/1:37:242.84:-25,-1,-4:20:9:10:9:10:0:0:0:9:10:0.53    0/1:50:314.79:-32,-1,-6:26:12:13:12:13:0:0:0:12:13:0.52
```

**Comment by brentp** [comment]
yes, those can occur if the alignment itself is not from an exclude chrom, but it has an SA to an exclude chrom. I may exclude these in the future but they are rare enough not to affect performance.

**Comment by brentp** [comment]
you can't pass any extra args. if you need to do that, you can just run duphold on its own and merge yourself. the --snp additions don't actually add a lot. I would leave them unless you have specific plans for them. as for extra bams, can you explain more what you mean?

**Comment by sbamin** [comment]
Got it and that's what I'd to do anyways as duphold step failed earlier due to issues with my LD_LIBRARY_PATH (libhts.so missing error). Agree and I can skip --snp part.

Sorry, I wrote that comment in hurry. extra bams option is related to `duphold -d or --drop`. I doubt if I can use that but that I can live with!

**Comment by sbamin** [comment]
Hi Brent,

All went well with both, joint calling and population level calling. I've now annotated sv calls with `--support 3` and `-d` filtered calls. I will further filter out germline and/or artifacts to get somatic calls based on genotypes and panel of normals. If there is a handy tool that you know about filtering based on genotypes (0/0 vs 0/1; 0/1 vs 1/1), please let me know else I will default to bcftools and awk/grep!

Thanks for all help and you may close this issue.

**Comment by brentp** [comment]
glad to hear it. I would use bcftools for that type of filtering.

**Comment by GuoYu-Peng** [comment]
> Hi Samir, glad to hear it's useful.
> 
> 1. is easier, but you might get more false positives.
> 
> I would do 1. with `--support 3` to the `smoove call` command.
> 
> For filtering, you can use the new duphold (-d) param when you do the final genotyping to give you an additional piece of information.

Hello, can I know why `--support 3` is used here?

**Comment by brentp** [comment]
requiring lower support will give higher sensitivity (but likely lower specificity).
