### ISSUE TITLE
Q about Input *

### ISSUE THREAD

**Issue by davemcg** [brentp/smoove#32]
Your examples make liberal use of *.FILE_ENDING. Is it possible to feed smoove comma separated input? Or space separated? 

I'll be integrating this into a Snakemake pipeline which tracks all the files, so there's little issue with wordiness.

**Comment by davemcg** [comment]
From clicking around random issues, it looks like space separated input works?

**Comment by brentp** [comment]
*.bam in bash effectively gets translated to space separated by the time smoove sees it.

**Comment by davemcg** [comment]
Thanks @brentp. Now that I've looked at smoove more closely I'm fairly certain I've wasted several hours  implementing lumpyexpress, SV-typer, etc myself. 

HPC people installed smoove quickly in a singularity container too!

**Comment by brentp** [comment]
great! let me know any problems.
too many hours have been spent re-implementing these things. :)
