### ISSUE TITLE
Docker latest isn't the latest

### ISSUE THREAD

**Issue by davemcg** [brentp/smoove#34]
I think I figured out why the HPC folks got confused (they thought they were installing 0.2.1 and 0.1.11 got installed)

If you run `docker pull brentp/smoove` you get 0.1.11

Running `docker pull brentp/smoove:v0.2.1` gets you 0.2.1

Of course now I can't verify as running `docker run brentp/smoove:latest smoove -version` throws an error (`docker run brentp/smoove:v0.2.1 smoove -version` works), but I'm pretty sure this was our issue.

**Comment by brentp** [comment]
this is fixed as of v0.2.2 which is the latest release.
