### ISSUE TITLE
"-p" doesn't work?

### ISSUE THREAD

**Issue by arkyl** [brentp/smoove#35]
Hi,
I was trying to speed up the smoove by increasing the threads number using "-p". However, so far "-p 8" on a 8 core machine and "-p 16" on a 16 core machine had the same runtime. I was running a single bam with the a command looking like this:
`smoove call -x --name  $name --exclude $exclude_bed_name --fasta $fasta_file_name -p $nts  --genotype  $bam_file`
The bam is 150bp pair end reads mapping on hg38, with ~50x coverage.
Any thoughts on this? Thanks a lot!

Yue

**Comment by brentp** [comment]
hi, thanks for trying it out. the -p command won't do too much with just a single sample. you can probably get some improvement up to 3 or 4 threads, but not much more than that.
the good news is that it should  take < 2 hours for a 50X bam even with 1 or 2 threads.

**Comment by arkyl** [comment]
Hi,
thanks for the quick response. I had two bam files run so far. One took 2h to run and the other took 20h. 

For the one that took 20h, just by reading the log after the following line:
`[smoove] 2018/11/14 20:23:39 > gsort version 0.0.6
[smoove] 2018/11/14 20:23:39 chr1	1000000
...
...
`
From chr1 output to chrY output, it took ~5h. For all the random and alt chrs, it took ~5.5h. From there to `wrote sorted, indexed file to smoove_out-smoove.genotyped.vcf.gz`, it took 7h. 

Do you have any thoughts about what might cause the slow runtime? Any suggestions to speed it up? Thanks a lot!

BTW, I also tested lumpyexpress in a docker image, it failed half way due to memory error. So I am thinking that more memory might speed up smoove? 

Yue

**Comment by arkyl** [comment]
[log.txt](https://github.com/brentp/smoove/files/2586479/log.txt)

Hi, 
I attach the log file. I ran it using a docker on DNAnexus. Thanks.

Yue

**Comment by brentp** [comment]
Yes, these files have > 70 million discordant reads. We normally see < 5 million for a 30X genome.
The next release with changes from @ernfrid will improve this quite a bit, but that sample is likely going to be problematic in other analyses as well.

**Comment by brentp** [comment]
yes, you can use ` --excludechroms`. it takes comma-delimited patterns. the default is: `hs37d5,~:,~^GL,~decoy` so you can add to make it, e.g.: `hs37d5,~:,~^GL,~decoy,~alt`

**Comment by arkyl** [comment]
That works quite well. The time is <9h. Thanks!
Yue

**Comment by brentp** [comment]
I'll close this for now. The pending release should also help this somewhat.
