### ISSUE TITLE
Smoove over-writes bam files

### ISSUE THREAD

**Issue by Phillip-a-richmond** [brentp/smoove#37]
Hello, 
I'm having trouble getting smoove to work, and I don't know how to debug this issue. Essentially, it looks like smoove is over-writing my bam file as soon as it starts, and then throws an EOF error. The error I get is:

[smoove] 2018/11/28 13:53:27 starting with version 0.2.2
[smoove] 2018/11/28 13:53:27 calculating bam stats for 1 bams
panic: unexpected EOF

goroutine 30 [running]:
github.com/brentp/goleft/covstats.pcheck(...)
	/home/brentp/go/src/github.com/brentp/goleft/covstats/covstats.go:30
github.com/brentp/goleft/covstats.BamStats(0xc000138960, 0x1312d0, 0x186a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/brentp/go/src/github.com/brentp/goleft/covstats/covstats.go:143 +0xc8c
github.com/brentp/smoove/lumpy.bam_stats.func1(0x1)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:197 +0x1f6
created by github.com/brentp/smoove/lumpy.bam_stats
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:211 +0x1a2

My actual command that I run with is:

`BAM=T014-1_BWAmem_dupremoved_realigned.sorted.bam
NAME=T014-1
OUTDIR=/mnt/causes-vnx2/TIDE/PROCESS/TIDE_GEL/T014/SMOOVE/
PROCS=16
GENOME_FASTA=/mnt/causes-vnx1/GENOMES/GSC/GRCh37-lite.fa

mkdir $OUTDIR

/opt/tools/smoove-0.2.2/smoove call \
        --name $NAME -p $PROCS \
        --outdir $OUTDIR \
        --genotype -f $GENOME_FASTA \
        $BAM
`

I thought it may be a samtools issue, but I'm using samtools v1.5. Do I need to use v1.9? I don't think I'm running the tool wrong since I followed exactly the code for a single bam file. Thanks for any help.

-Phil

**Comment by brentp** [comment]
what does `samtools quickcheck $BAM` show?

**Comment by Phillip-a-richmond** [comment]
No output is shown when I run that command.

**Comment by Phillip-a-richmond** [comment]
I ran it on another bam file generated the same way, since smoove literally over-writes the BAM file that I give it (file size 0).

**Comment by brentp** [comment]
can you share a part of the bam that reproduces the error?

**Comment by Phillip-a-richmond** [comment]
It is over-writing any bam file I give it on this system. I don't think passing you parts of a bam file will help the situation. 

I'm going to try with a fresh install of the latest tools to see if that mitigates the error. 

Is there a conda .yml with all of the latest tools for version 0.2.2? 

-Phil

**Comment by brentp** [comment]
I only have the docker container. Updating to htslib, samtools > 1.8 might be a good thing to try.

**Comment by Phillip-a-richmond** [comment]
Fixed the issue with samtools for coverage calculation. 

And then another issue popped up with lumpy_filter, likely because my lumpy-sv old version threw the error. 

[smoove] 2018/11/28 17:22:25 starting with version 0.1.9
[smoove] 2018/11/28 17:22:25 calculating bam stats for 1 bams
[smoove] 2018/11/28 17:22:28 done calculating bam stats
[smoove]: ([E]lumpy-filter) 2018/11/28 17:22:36 [E::hts_open_format] fail to open file '-f'
[smoove]: ([E]lumpy-filter) 2018/11/28 17:22:36 lumpy_filter: Unable to open BAM/SAM file.
[smoove]:2018/11/28 17:22:36 finished process: lumpy-filter (lumpy_filter -f /mnt/causes-vnx1/GENOMES/GSC/GRCh37-lite.fa 17D8290_dedup.bam /mnt/causes-vnx2/TIDE/) in user-time:3.18ms system-time:8.913153s
[smoove]:2018/11/28 17:22:36 error running command: lumpy_filter -f /mnt/causes-vnx1/GENOMES/GSC/GRCh37-lite.fa 17D8290_dedup.bam /mnt/causes-vnx2/TIDE/PROCESS/GENOME_TIDEX/T308/TestSmoove/TMP//17D8290.split.bam.tmp.bam /mnt/causes-vnx2/TIDE/PROCESS/GENOME_TIDEX/T308/TestSmoove/TMP//17D8290.disc.bam.tmp.bam 2 && mv /mnt/causes-vnx2/TIDE/PROCESS/GENOME_TIDEX/T308/TestSmoove/TMP//17D8290.split.bam.tmp.bam /mnt/causes-vnx2/TIDE/PROCESS/GENOME_TIDEX/T308/TestSmoove/TMP//17D8290.split.bam && mv /mnt/causes-vnx2/TIDE/PROCESS/GENOME_TIDEX/T308/TestSmoove/TMP//17D8290.disc.bam.tmp.bam /mnt/causes-vnx2/TIDE/PROCESS/GENOME_TIDEX/T308/TestSmoove/TMP//17D8290.disc.bam -> exit status 1
panic: exit status 1

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7ffe43eb8ef2, 0x7, 0x7ffe43eb8f56, 0x2b, 0x7ffe43eb8f08, 0x3f, 0xc420123410, 0x1, 0x1, 0xc420266000, ...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:115 +0x556
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:275 +0x23a
main.main()
	/home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:115 +0x1dd


I should be able to mitigate these issues, but I guess I'm wondering why the original bam files are getting over-written? Is smoove holding on to them somehow and then trashing the filename when it errors-out? I've never seen that behaviour before...

Is it possible that the issue is I'm not giving a full file path, just the name of the bam file? And you make some assumption about being able to write a tmp file to the path where the bam lives? 

I'll try a few more things on my end then report back and/or close.

Cheers,
Phil

**Comment by Phillip-a-richmond** [comment]
Yes indeed that is the issue. When I replace the bam name with the full file path to the bam file, I no longer get the over-write issue when it errors out. 

Look forward to using this more now!

Thanks for the great tools! (And maybe put a warning about not using the full file path).

Cheers,
Phil

**Comment by brentp** [comment]
oh, you were using an older version of lumpy_filter! I'll see if I can guard against that.
