### ISSUE TITLE
Filtering SV Calls

### ISSUE THREAD

**Issue by Phillip-a-richmond** [brentp/smoove#42]
So I'm using Smoove in our pipeline for rare disease diagnosis, but most of the calls are difficult to filter. 

I really liked the analysis within https://www.nature.com/articles/s41525-018-0061-8 (EIEE WGS paper 2018), and specifically I was wondering, from smoove output, what's the best way to apply this filter?

"Candidate de novo structural mutations were identified by screening the LUMPY SV predictions in each family for variants where the proband had a variant genotype, and both parents had homozygous reference genotypes. We further required the proband to have at least 15 alignments (paired-end or split-read) supporting the de novo SV and each parent to have zero supporting reads. We then removed SVs where either end overlapped a simple repeat defined by the UCSC genome browser for build 37 of the human genome. After these steps, only two SVs remained: the translocation in family 42,610, and the duplication in family 44,133."

Is this something that is done with vcftools on the resulting VCF file from Smoove?

Thanks,
Phil

**Comment by brentp** [comment]
Smoove was not used in those calls. But you can use bcftools or [GQT](https://github.com/ryanlayer/gqt) or [cyvcf2](https://github.com/brentp/cyvcf2) to do this type of filtering.
You might also check out the new vcf plotter in [samplot](https://github.com/ryanlayer/samplot) it's not documented yet, but you can give it expressions to filter by sample and it will show de novo variants if you give it a ped file.
