### ISSUE TITLE
Number of variants differ between merge and genotyped files

### ISSUE THREAD

**Issue by dfermin** [brentp/smoove#45]
Hello.

I'm able to run smoove call, merge and then genotype.
When I try to run the `smoove paste` function I hit this error:

```
[smoove] 2018/12/13 08:46:43 starting with version 0.2.2
[smoove] 2018/12/13 08:46:43 squaring 613 files to smoove/results-pasted/cohort1.smoove.square.vcf.gz
[smoove] 2018/12/13 08:47:25 613 files had 9363 variants
[smoove] 2018/12/13 08:47:25 files: smoove/results-genotyped/samp_123.genotyped.vcf.gz had 9365 variants
[smoove] 2018/12/13 08:47:25 files: smoove/results-genotyped/samp_918.genotyped.vcf.gz,smoove/results-genotyped/samp_332.genotyped.vcf.gz  had 9364 variants
[smoove] 2018/12/13 08:47:25 please make sure that all files have the same number of variants
```

The merge output (call it `merge.sites.vcf.gz`) contains 9363 variants. 
One of the samples in my data set (call it `samp_123.genotyped.vcf.gz`) contains 936**5** variants.

A quick check with 
```
vcftools --gzvcf merge.sites.vcf.gz --gzdiff samp_123.genotyped.vcf.gz --diff-sites --stdout | grep -w '\.' -A1 -B1
``` 

shows me this output:

```
1       70107418        70107418        B       N       N       <DUP>   <DUP>
1       .       70107418        2       .       N       .       <DUP>
1       70259625        70259625        B       N       N       <DEL>   <DEL>
--
1       70375190        70375190        B       N       N       <DUP>   <DUP>
1       .       70375190        2       .       N       .       <DUP>
1       70375403        70375403        B       N       N       <DEL>   <DEL>
```

So 2 variants have two entries in `samp_123.genotyped.vcf.gz` 

I know what the problem is but I'm not sure how fix it. I could filter on the sites in the merge.sites.vcf.gz file but I'm wondering why the `smoove merge` step didn't catch and address this. Perhaps it can and I just don't know the command.
Is there an smoove-specific command/option/function I can use to fix this?

Thanks,
Damian

**Comment by brentp** [comment]
hmm. 
can you re-genotype `samp_123.genotyped.vcf.gz` ? using the `merge.sites.vcf.gz` file?

if the difference in numbers persists, can you share the sites.vcf.gz and the sample bam so I can debug?

**Comment by brentp** [comment]
no idea. if you can consistently reproduce then I can take a look. we've run smoove on thousands of samples and not seen this so it must be something peculiar about your set.

**Comment by dfermin** [comment]
I'll chalk it up to my data. The problem is detectable and can be overcome by rerunning the genotype step.

**Comment by brentp** [comment]
This may be related to #48 .
If you continue to experience this problem. Please post there as any additional info would be helpful.
Thanks for reporting.
