### ISSUE TITLE
Segfault running smoove annotate

### ISSUE THREAD

**Issue by dfermin** [brentp/smoove#46]
Last hurdle!
I'm running the final step after `smoove paste` to annotate the final VCF and I'm getting a segfault. 
This error seems reproducible. I consistently get this message when I run `smoove paste`.

```
smoove annotate --gff ~/ref_files/gencode.v28lift37.annotation.gff3.gz results-pasted/chr1.smoove.square.vcf.gz | bgzip -c > final_vcfs/chr1.smoove.square.annot.vcf.gz
[smoove] 2018/12/14 08:33:10 starting with version 0.2.2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6d5213]

goroutine 1 [running]:
github.com/brentp/smoove/annotate.setSmooveQuality(0xc000190340, 0xc000190340)
	/home/brentp/go/src/github.com/brentp/smoove/annotate/annotate.go:355 +0x113
github.com/brentp/smoove/annotate.annotate(0xc0042a8940, 0xc004111f20, 0xc000166de0)
	/home/brentp/go/src/github.com/brentp/smoove/annotate/annotate.go:380 +0xe1
github.com/brentp/smoove/annotate.Main()
	/home/brentp/go/src/github.com/brentp/smoove/annotate/annotate.go:439 +0x467
main.main()
	/home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:123 +0x1d7
```

I know the annotation step is optional so this might not be necessary. However I would like to get the **MSHQ** score for the calls to work with. If this could be obtained some other way I'll happily go that root.

Thanks!

**Comment by brentp** [comment]
can you share a part of the vcf that recreates the error?

MSHQ is useful, but I wrote it before [duphold](https://github.com/brentp/duphold) existed. So if you ran smoove genotype with `-d` then you'll have the duphold annotations which are very good for discerning real from spurious.

**Comment by dfermin** [comment]
I can share it but via email (not on a public forum).
Do you have an academic (.edu) address I can email the VCF to?

**Comment by brentp** [comment]
I only use my gmail: bpederse@gmail.com

**Comment by brentp** [comment]
instead of this:
```
smoove paste -n chr1_redo ./results-genotyped/chr1/*.vcf.gz
```
maybe you need to do something more specific that doesn't get files that smoove can't paste. you're probably getting the called files as well.

**Comment by dfermin** [comment]
Each step of the pipeline gets it's own output directory:
```
results-call/chr1
results-merged
results-genotyped/chr1
results-paste
```
So I'm not getting the called files mixed in.

I can break up the paste command into chunks of files (say 10 samples at a go). Then use `bcftools merge` to put them together.
In the interest of efficiency is there a way to detect which fils smoove won't be able to paste ahead of time?

**Comment by brentp** [comment]
this is very hard to debug without more information.
can you post each command that you ran? are you checking that each process exits successfully?
presumably, you could see which files are ok in your genotyped dir by doing:
```
ls results-genotyped/*.vcf.gz | xargs -I{} bcftools view {} > /dev/null
```

**Comment by brentp** [comment]
well, this is showing that you ran: `bcftools annotate -x INFO/PRPOS,INFO/PREND`
that means you probably ran `smoove call` with the -x command, eh? That wont work for joint genotyping.

**Comment by brentp** [comment]
hmm. well, you are right. it is ok to use -x for step 3. if you can get me the files and the exact commands, I might be able to help you further.
