### ISSUE TITLE
Behaviour of the --exclude option

### ISSUE THREAD

**Issue by dminkley** [brentp/smoove#49]
Hello,

I'm curious what the exact behaviour of the --exclude option is.  The documentation says it can be used to 'remove problematic regions' - how does it do this?  Does it ignore evidence from problematic regions (ie reads mapping in these regions can't offer support for a variant), or does it remove variants which span such a region?

Thanks,

David

**Comment by brentp** [comment]
Hi, that just means that reads that overlap the `--exclude` regions will not be sent to lumpy. I'll clarify this in the documentation before the next release.
