### ISSUE TITLE
Smoove filling up TMP space and not listening to TMPDIR

### ISSUE THREAD

**Issue by dminkley** [brentp/smoove#50]
Hello!

I've been using smoove (genotype, specifically) recently, and had an issue with it filling up my default tmp space during a large run.  I tried setting the TMPDIR environment variable (as well as TEMP and TMP) to point a location with more space, but smoove appears to be ignoring it.  Is there a way to set the tmp directory used by smoove?  If not, could this be added in a future release (either respecting TMPDIR or a --tmp option)?

Thanks!

-David

**Comment by brentp** [comment]
Hi David, thatnks for reporting. Can you verify that you are doing `export TMPDIR=/somewhere` and not just `TMPDIR=/somewhere`? And can you let me know what tmp files or contents are getting sent to the wrong place?

**Comment by dminkley** [comment]
Hi Brent - you're completely right, I'd forgotten to use export.  Never mind me, everything seems to be working properly!  You can probably close this.

-David

**Comment by brentp** [comment]
ok. great! I am tracking down bugs now so let me know any other issues.
