### ISSUE TITLE
Comparison to GRIDSS

### ISSUE THREAD

**Issue by DarioS** [brentp/smoove#52]
Smoove is a post-processing tool that improves specificity of Lumpy results. I found a more recent tool from 2017, [GRIDSS](https://genome.cshlp.org/content/27/12/2050), which did benchmarking against Lumpy and appeared to have superior performance. Now I'm wondering how the combination on Lumpy and smoove performs in comparison to GRIDSS. Is there any benchmarking available to help decide? Looking at the Latest Releases of Lumpy, the last one, 0.2.13, was almost 3 years ago, so I'd naively tend to choose something more recently updated if there was no benchmarking. But, in another smoove issue, you mentioned that you processed over 50000 samples using Lumpy, so that makes it appealing on the other hand.

**Comment by brentp** [comment]
If you look at their figure: https://genome.cshlp.org/content/27/12/2050/F3.large.jpg they are barely better than vanilla lumpy. I suspect with the improvements to smoove and svtyper and using duphold annotations, you'll get better from smoove and use much less CPU time.
