### ISSUE TITLE
Why doesn't AS + AP = SU?

### ISSUE THREAD

**Issue by JoWhi** [brentp/smoove#53]
have run smoove then duphold on 46 individuals, then pasted the duphold output back into a squared vcf with all 46 samples. I have been using SU/AC as one of my filters, looking for variants that have a minimum threshold of support per alternate allele called. Now I'm confused by some of the variants that are getting filtered out, and wonder why SU (number of pieces of evidence supporting the variant) is not calculated as I had expected.

For one variant, if I sum the AS values (split-read observation counts) and the AP values (paired-end observation counts) over all 46 individuals, I get AS=24 and AP=15, so 39 total reads supporting the variant in the population. However, SU is only 14 (PE=5 + SR=9).

Can anyone tell me why the values for SU, PE, SR are so much lower than the total AS & AP counts? Thank you!

**Comment by brentp** [comment]
SU, PE, SR are calculated by lumpy. The others are by svtyper. If you ran lumpy for each sample, then did a merge, the confidence intervals (which are then used by svtyper) could be larger or smaller. This could affect the counts.
I would have to know more about how exactly you ran the cohort to give more detail, but I don't think this is too surprising.
