### ISSUE TITLE
How specifically does one satisfy lumpy_filter dependency?

### ISSUE THREAD

**Issue by jbsysadmin** [brentp/smoove#57]
Greetings. I tried to install smoove-0.2.3. All dependencies are met, except one. When calling smoove, lumpy_filter is missing. The build instructions here and for lumpy-sv v0.2.13 make no direct allowance for "lumpy_filter."

How is the user supposed to build or include such a dependency? Thanks for any leads.

**Comment by brentp** [comment]
if you type `make` in the lumpy-sv source there will be `lumpy` and `lumpy_filter` in the `bin/` directory. so you can do `export PATH=$PATH:/path/to/lumpy-sv/bin/` and lumpy_filter should be available in your $PATH.

**Comment by jbsysadmin** [comment]
That’s what I thought! But here are the contents of bin:

lumpy
lumpyexpress
lumpyexpress.config

Please advise,
-John

**Comment by brentp** [comment]
you must have an old version of lumpy. you'll need to update (git pull) to get a recent version.

**Comment by jbsysadmin** [comment]
That, and running make all (instead of make) worked.
Thank you.
