### ISSUE TITLE
Empty VCF header reference attribute in VCF files produced via Smoove commands

### ISSUE THREAD

**Issue by WimSpee** [brentp/smoove#58]
I get this downstream error when trying to read a SV VCF file created with Smoove.
```
    raise ValueError("Empty VCF header reference attribute is not allowed. Check VCF/BCF header for the 'reference' value.")
ValueError: Empty VCF header reference attribute is not allowed. Check VCF/BCF header for the 'reference' value.
```

In the final pasted square VCF the reference attribute is indeed empty.  
This also the case in all the intermediate VCF files (each call VCF, the merged sites VCF, each genotype VCF)
```
##reference=
```

The  Smoove call, merge and genotype commands require the fasta on the command line. So it should be possible to set this attribute in the header for the intermediate and the final pasted VCF.

**Comment by brentp** [comment]
I can get this into the next release, but I'm pretty sure this is not required by the spec, so your parser is a bit over-zealous.

**Comment by WimSpee** [comment]
Thank you. It is indeed just an internal requirement, not in the part of the VCF spec.
 In some scripts  we use the VCF header to find back FASTA file used to create the file. 

Thank you for adding it.
