### ISSUE TITLE
tumour normal call

### ISSUE THREAD

**Issue by Sames-Jtudd** [brentp/smoove#60]
Hi, 
Im using smoove to call SVs in tumour material, great tool easy to use. I would like to call somatic SVs
Im not exactly sure what the correct procedure is. I have read the previous post regarding a similar problem and the documentation from smoove and Lumpy and these didn't quite cover the issue, I was hoping you could help.
Following the scheme in Lumpy express of listing the two files (tumour/normal) sequentially, I executed the the smoove command ; 

smoove call --outdir smoove_output --exclude exclude_regions.bed --name INF001 --fasta $ref_genome -p `nproc` --genotype $tumour_bam $normal_bam

This outputs a file "INF001-smoove.genotyped.vcf.gz"  which appears to be a cohort bam but I'm unsure how on the basis of this to extract the somatic calls?

thanks 

jamie

**Comment by brentp** [comment]
hi, smoove simply calls and genotypes SVs. It's outside of the scope of the project to determine which are somatic. You could probably do some simple downstream filtering to find, for example variants in tumor that  have no evidence in normal.

**Comment by Sames-Jtudd** [comment]
Thanks for the reply
