### ISSUE TITLE
difference in the number of variants called depending on whether samples are called individually or in pairs

### ISSUE THREAD

**Issue by Sames-Jtudd** [brentp/smoove#61]
Hi, great tool, sorry to bother.
I've been playing around with different ways of calling SVs. I'm interested in somatic variants so I compared the results obtained by 1) joint calling a tumour/normal pairs and 2) calling the normal from the merge of the tumour. In either case filtering for those variants with evidence only in the tumor sample (ie the matched normal has AO=0).  
ie  1) joint call 
$smoove call --name BLAH --exclude exclude.bed --fasta ref.fa -p $(nproc) --genotype normal.bam tumour.bam

2) tumor call first then merge and call the normal  
$smoove call --name BLAH --exclude exclude.bed --fasta ref.fa -p $(nproc) --genotype tumour.bam
$smoove merge --name merged --fasta ref.fa --outdir ./ results-smoove/tumour.genotyped.vcf.gz
$smoove genotype -d -x -p 1 --name joint --outdir results-genotped/ --fasta ref.fa --vcf merged.sites.vcf.gz normal.bam 

When I do this I get a different number of variants with evidence only in the tumour sample. 
All of those SVs called by the (2) sequential method are called by joint calling (1) method. But there are additional SVs called only by the joint method. Unless I've missed something, which is defo possible, this should not be true?  
As for why I don't just joint call and filter, Im using cloud based computing and its about 10x the cost to joint call due to resource requirements. 

many thanks 

jamie

**Comment by brentp** [comment]
unfortunately, this is not unexpected. When you do the merge on the separately called samples, it combines the confidence intervals of the 2 samples. this can sometimes result in a widening that's different between svtools [which smoove uses for merging] and lumpy which does the CI internally with jointly-called samples. the variants that are different between these approaches should be mostly lower quality.

Also, there is a min-support parameter that is summed across samples, so when you have more samples in the joint call, it's possible you are reaching the threshold for some cases when you do not in the single-sample case.

**Comment by Sames-Jtudd** [comment]
thanks for getting back, yeah I did notice that they tended to be lower quality SVs. 
basically just happy its not me messing it up.
cheers
