### ISSUE TITLE
Cannot run smoove from docker

### ISSUE THREAD

**Issue by nelsonchanhk** [brentp/smoove#69]
Hello, I'm new to smoove. I've pulled the docker image and tried to run it locally.
That's an error as follows. But the "missing file" is obviously inside the same folder. Am I having a wrong syntax? Please kindly help. Thank you!

nelson@Ubuntu-testing ~/OPERATION/RedCellNGS/Processed_bam_vcf_1/bam

$ ls HBD1.bam
HBD1.bam
(base) 
nelson@Ubuntu-testing ~/OPERATION/RedCellNGS/Processed_bam_vcf_1/bam
$ docker run -it brentp/smoove smoove call -x --name RBC --fasta ~/OPERATION/RedCellNGS/ref/Homo_sapiens_assembly38.fasta -p 20 --genotype ./HBD1.bam
[smoove] 2019/05/03 15:41:35 starting with version 0.2.3
panic: open ./HBD1.bam: no such file or directory

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.check(...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:54
github.com/brentp/smoove/lumpy.lumpy_filter_cmd(0x7fffeab05f69, 0xa, 0x9eb544, 0x2, 0x7fffeab05f14, 0x43, 0x0, 0x0, 0x0, 0x0, ...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:83 +0x134b
github.com/brentp/smoove/lumpy.Lumpy(0x7fffeab05f08, 0x3, 0x7fffeab05f14, 0x43, 0x9eb544, 0x2, 0xc0000995d0, 0x1, 0x1, 0xc0001941e0, ...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:119 +0x145
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:334 +0x277
main.main()
	/home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1d7
(base)

**Comment by brentp** [comment]
this is a docker issue. you need to use one or more [volumes](https://docs.docker.com/storage/volumes/) to allow docker access to the files on your machine. By default, it has no access to anything on your machine.

**Comment by nelsonchanhk** [comment]
Thanks a lot brentp, problem solved.
