### ISSUE TITLE
report error panic: open /store/gchen/smoove/100.bam: no such file or directory

### ISSUE THREAD

**Issue by ChenDepp** [brentp/smoove#75]
![QQ截图20190612195218](https://user-images.githubusercontent.com/48479509/59349190-985ff580-8d4b-11e9-8f12-56fa84895e4f.png)
can you tell me how to solve it ,thank you very much!

**Comment by brentp** [comment]
you need to give your docker container access to that directory, you can do, e.g.

docker run -v `pwd`:/store/ -v `pwd`/results:/results/` ...

both your inputs and output directories have to be mapped to volumes within docker.

**Comment by ChenDepp** [comment]
![QQ截图20190613104751](https://user-images.githubusercontent.com/48479509/59400449-0b0fb600-8dca-11e9-8b02-24fa7cb8e44d.png)
how are you brentp?
       when i running the program it will report the error,i don't know how to solve it? can you tell me how to solve it? thank you very much!

**Comment by brentp** [comment]
you bams needs to have read-groups. you can add them with `samtools addorreplacerg`

**Comment by ChenDepp** [comment]
hello brentp,
    i know how to solve it
    but i have a question about the smoove.my sequencing data just have 7 depth (average)，it will influence the SV number find ? thank your ?

**Comment by brentp** [comment]
yes, depth 7 is low and far from ideal., but you should be able to find a few SVs, you can also set `--support 3` so it will only require 3 pieces of evidence supporting the event.

**Comment by ChenDepp** [comment]
thank your! 
    How deep is it right?， I only have a part of sample  depth greater than 10, most of which are below 10.
