### ISSUE TITLE
merge tissue

### ISSUE THREAD

**Issue by ChenDepp** [brentp/smoove#76]
![QQ截图20190614095942](https://user-images.githubusercontent.com/48479509/59478497-0dd2df80-8e8c-11e9-8e92-a7d29547bbd6.png)
hello brentp!
    when i merge the vcf file,it report the error ,can you tell me how to solve it? thank your

**Comment by brentp** [comment]
that error is indicating that your numpy installation is broken. can you show the full error in text, not image?

**Comment by ChenDepp** [comment]
root@b66aec3f537b:/store/gchen/smoove# smoove merge --name merged --outdir ../results/ -f GDDH13_1-1_formatted.fasta                                                                                              ../results/*.genotyped.vcf.gz
[smoove] 2019/06/14 02:02:39 starting with version 0.2.3
[smoove] 2019/06/14 02:02:39 merging 209 files
[smoove] 2019/06/14 02:02:39 finished sorting 209 files; merge starting.
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/special/__init__.py:640: RuntimeWarning: nu                                                                                            mpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.d                                                                                            type size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/linalg/__init__.py:207: RuntimeWarning: num                                                                                            py.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: n                                                                                            umpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning                                                                                            : numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dty                                                                                            pe size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarn                                                                                            ing: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWar                                                                                            ning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._tools import csgraph_to_dense, csgraph_from_dense,\
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarn                                                                                            ing: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._traversal import breadth_first_order, depth_first_order, \
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarn                                                                                            ing: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._min_spanning_tree import minimum_spanning_tree
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarn                                                                                            ing: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:95: RuntimeWarning: num                                                                                            py.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:96: RuntimeWarning: num                                                                                            py.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWa                                                                                            rning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/spatial/distance.py:122: RuntimeWarning: nu                                                                                            mpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/optimize/_trlib/__init__.py:1: RuntimeWarni                                                                                            ng: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._trlib import TRLIBQuadraticSubproblem
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/optimize/_numdiff.py:10: RuntimeWarning: nu                                                                                            mpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._group_columns import group_dense, group_sparse
[smoove] 2019/06/14 02:02:40 /usr/local/lib/python2.7/dist-packages/scipy/stats/_continuous_distns.py:18: RuntimeWarn                                                                                            ing: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _stats
### may is scipy problem?

**Comment by ChenDepp** [comment]
hello brentp, 
         can i uninstall numpy,and reinstall it?

**Comment by brentp** [comment]
yes, you can try that. google that error.

**Comment by ChenDepp** [comment]
@brentp ,thank your help very much!,it running successfully!

**Comment by brentp** [comment]
glad to hear it.
