### ISSUE TITLE
smoove paste problem 

### ISSUE THREAD

**Issue by ChenDepp** [brentp/smoove#78]
hello,brentp
      
![微信截图_20190622141325](https://user-images.githubusercontent.com/48479509/59960241-414ee300-94f8-11e9-82a8-75f6d5fdffb4.png)
    running the command smoove paste,the input file is the output file of smoove call? 
![微信截图_20190622141358](https://user-images.githubusercontent.com/48479509/59960250-7824f900-94f8-11e9-8ca9-76504de6d912.png)

**Comment by brentp** [comment]
it's the output of smoove genotype. note the difference in directories `results-smoove` for step 1. vs `results-genotyped` for step 4.

**Comment by ChenDepp** [comment]
hello brentp! 
  when i running the smoove paste command it report the error! 
    the step 4,it output one file ? 
     
![微信截图_20190624170802](https://user-images.githubusercontent.com/48479509/60006435-00df9880-96a3-11e9-8e59-f5de06c6ffc0.png)
please tell me how to solve  it ?

**Comment by brentp** [comment]
you probably have an old version of bcftools. Just update that and try again.

**Comment by brentp** [comment]
please re-open if updating bcftools does not resolve your issue.
