### ISSUE TITLE
BND

### ISSUE THREAD

**Issue by tyyiyi** [brentp/smoove#81]
Hello, I am a newcomer to smoove, it is a good tool. When I was using smoove call, I couldn't understand the results it returned to me. What does BND mean?

#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT T1 N1
Chr1 216981736 38_1 N ]CHR2:63550226]N 105.51 . SVTYPE=BND;STRANDS=- :6;IMPRECISE;CIPOS=-10,9;CIEND=-9,8;CIPOS95=0,0;CIEND95=-1,1 ;MATEID=38_2;EVENT=38;SU=6;PE=2;SR=4;PRPOS=9.5249e-17,3.79675e-15,1.51329e-13,6.03128e-12,2.4039e-10,9.58017e -09,3.81765e-07,1.52142e-05,0.00060631,0.024163,0.961958,0.0130764,0.000177755,2.41633e-06,3.28465e-08,4.46502e-10,6.06955e-12,8.25068e-14,1.12156e -15,1.5246e-17;PREND=4.20369e-16,3.09242e-14,2.27491e-12,1.67352e-10,1.23111e-08,9.05658e-07,6.66241e-05,0.00490115,0.265233,0.360357 ,0.36017,0.0090376,0.000226787,5.69068e-06,1.42791e-07,3.58284e-09,8.98915e-11,2.25528e-12;AC=1;AN=4 GT:GQ:SQ:GL:DP:RO :AO:QR:QA:RS:AS:ASC:RP:AP:AB 0/1:3:103.47:-11,-1,-1:9:3:5:2:4:1:3:0 :1:1:0.67 0/0:3:2.04:-0,-0,-1:2:2:0:1:0:0:0:0:1:0:0

Chr10 61190401 76_1 N N[CHR16:69581033[ 0 . SVTYPE=BND;STRANDS= -:6;CIPOS=-8,8;CIEND=-10,9;CIPOS95=0,0;CIEND95=0,0;MATEID= 76_2; EVENT=76; SU=6; PE=2; SR=4; PRPOS=2.04952e-15, 1.50771e-13, 1.10914e-11, 8.15928e-10, 6.00231e-08, 4.41556e-06, 0.000324827,0.0238956,0.95129,0.0238702,0.000598978,1.503e-05,3.77168e-07,9.46407e-09,2.3745e-10,5.95779e-12,1.49477e-13;PREND=9.5249e-17,3.79675e- 15,1.51329e-13,6.03128e-12,2.4039e-10,9.58017e-09,3.81765e-07,1.52142e-05,0.00060631,0.024163,0.961958,0.0130764,0.000177755,2.41633e-06,3.28465e- 08,4.46502e-10,6.06955e-12,8.25068e-14,1.12156e-15,1.5246e-17;AC=2;AN=2 GT:GQ:SQ:GL:DP:RO:AO:QR: QA: RS: AS: ASC: RP: AP: AB 1/1: 2: 31.46: -3, -0, -0: 2:0:1:0:1:0:0:0:0:1: 1 ./.:.:.:.:0:0:0:0:0:0:0:0:0:0:.

What do “] CHR2:63550226]N” and “N[CHR16:69581033[” in these two examples stand for?
And what does normal GT=./. mean?
I hope to get your help, thank you.

**Comment by brentp** [comment]
you can refer the to the [vcf spec](https://samtools.github.io/hts-specs/VCFv4.2.pdf) for full details on what these mean. lumpy will assign an SV as type of BND if it doesn't meet the standard pattern (read orientation) or DEL/DUP/INV.
