### ISSUE TITLE
error message "couldn't get region from line"

### ISSUE THREAD

**Issue by TendoLiu** [brentp/smoove#82]
Hi Guys,
   I am using smoove recently on targeted DNAseq files.

My code: 
smoove call -x \
--name Lumpy \
--outdir $out \
--exclude $ExcludeBed \
--fasta $hg19_fasta \
-p 1 \
--genotype $testBam

Output file:
[smoove] 2019/08/08 18:37:57 starting with version 0.2.3
[smoove] 2019/08/08 18:37:57 calculating bam stats for 1 bams
[smoove]: ([E]lumpy-filter) 2019/08/08 18:39:18 [lumpy_filter] extracted splits and discordants from 2564470 total aligned reads
[smoove]:2019/08/08 18:39:18 finished process: lumpy-filter (set -eu; lumpy_filter -f /bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusi) in user-time:1m42.137273s system-time:12.3704s
[smoove] 2019/08/08 18:42:52 done calculating bam stats
2019/08/08 18:43:12 couldn't get region from line

Does anybody know what kind of error is this and how to fix it?
Appreciate it a lot.

[Lumpy.txt](https://github.com/brentp/smoove/files/3494336/Lumpy.txt)
[LumpyOut.txt](https://github.com/brentp/smoove/files/3494337/LumpyOut.txt)

**Comment by brentp** [comment]
you probably have an empty (or otherwise invalid) line in `$ExcludeBed`

**Comment by TendoLiu** [comment]
> you probably have an empty (or otherwise invalid) line in `$ExcludeBed`

Thanks. I realized that it was probably because I am using b37 ExcludeBed file downloaded from here. Any idea where to find a hg19 version?

**Comment by brentp** [comment]
no, that wouldn't cause this error. I would head or zless the file and see what it looks like. you can just prepend chr to get ht19. it will work the same.

**Comment by TendoLiu** [comment]
Thanks. You are right. It looks like this. Did not make any change to the original file. Used wget to download the file directly to the directory. SHould I just delete all the empty lines?





<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <l

**Comment by TendoLiu** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">

**Comment by TendoLiu** [comment]
<blank>
<blank>
<blank>
<blank>
<blank>
<blank>
<!DOCTYPE html>
<html lang="en">
  <head>

**Comment by TendoLiu** [comment]
Problem solved. Should have used wget. Should save the bed file directly.
Thanks for the response!
