### ISSUE TITLE
Docker update?

### ISSUE THREAD

**Issue by ctsa** [brentp/smoove#84]
The smoove docker release is really helpful. Is this going to be updated going forward? I just checked https://hub.docker.com/r/brentp/smoove and it looks like this is still on v0.2.3. Thanks!

**Comment by brentp** [comment]
updated. thanks for the reminder. if you compare to manta for deletions (and be sure to use -d to run duphold), i'd be interested to see the results. I have been recommending manta as I've found it does quite well for smaller stuff (which lumpy cannot find).

**Comment by ctsa** [comment]
Thanks for the quick update Brent, I'll be sure to add the -d option.
