### ISSUE TITLE
svtyper missing in Docker image

### ISSUE THREAD

**Issue by calkan** [brentp/smoove#87]
svtyper is not in the Docker image. 

from brentp/smoove :

root@e825e74f3bd9:/# smoove 
smoove version: 0.2.4

smoove calls several programs. Those with 'Y' are found on your $PATH. Only those with '*' are required.

 *[Y] bgzip [ sort   -> (compress) ->   index ]
 *[Y] gsort [(sort)  ->  compress   ->  index ]
 *[Y] tabix [ sort   ->  compress   -> (index)]
 *[Y] lumpy
 *[Y] lumpy_filter
 *[Y] samtools
 *[ ] svtyper
 *[Y] mosdepth [extra filtering of split and discordant files for better scaling]

**Comment by Flope** [comment]
I have the same issue using singularity. 
What version works?
I don't see it in your git, calkan/smoove

> using the same image:
> 
> brentp/smoove latest 92d4e938c642 4 weeks ago 2.69GB
> 
> I added svtyper in the image myself (calkan/smoove); that version works

**Comment by brentp** [comment]
hi, svtyper is in the docker image, but singularity somehow messes it up on the conversion. you can get around that by using this command to create the singularity container:

```
docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/output --privileged -t singularityware/docker2singularity  brentp/smoove:v0.2.4
```

see: https://github.com/brentp/smoove/issues/85#issuecomment-523654711

so, I consider this to be a singularity issue, not a smoove issue.
