### ISSUE TITLE
docker merged层的目录损坏无法访问

### ISSUE THREAD

**Issue by pengmhm** [brentp/smoove#88]
访问损坏的目录提示：No such file or dir 
在容器层目录和镜像层目录都能够 正确访问，但是镜像挂载层无法访问。
重启docker之后损坏的目录在容器里可以被访问到。

**Comment by brentp** [comment]
have a look at #85 and #87

**Comment by pengmhm** [comment]
我看了一下您的回复，发现另外两个问题和我所提的问题并不完全一样，我没明白的是在容器层我的目录为什么会莫名其妙的损坏。

**Comment by pengmhm** [comment]
There is no way to reproduce this problem now.

This is a problem I have encountered before.

**Comment by brentp** [comment]
docker -> singularity is fixed in 0.2.5
