### ISSUE TITLE
Unknown error when running smoove docker file.

### ISSUE THREAD

**Issue by TendoLiu** [brentp/smoove#91]
testbam=/bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/SecondPanel/0_Illumina_UMI_Error_Corrected_bam/Sample1.collapsed.bam

out=/bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/SecondPanel/1_SVcalling/Lumpy/Results/

ExcludeBed=/bgfs/soesterreich/pan_data/soesterreich/Tendo/InstalledTools/Smoove/ceph18.b37.lumpy.exclude.2014-01-15.bed

#################### Run package ####################
Command line:
singularity exec -B /bgfs:/bgfs /ihome/crc/install/smoove/smoove_v0.2.3.img \
smoove call -x \
--name Lumpy \
--outdir $out \
--exclude $ExcludeBed \
--fasta $hg19_fasta \
-p 1 \
--genotype $testbam

Error: 
[smoove] 2019/10/23 18:25:43 done calculating bam stats
[smoove] 2019/10/23 18:25:44 removed 0 alignments out of 98 (0.00%) with low mapq, depth > 1000, or from excluded chroms from Sample1.disc.bam in 1 seconds
[smoove] 2019/10/23 18:25:44 removed 1 alignments out of 98 (1.02%) that were bad interchromosomals or flanked-splitters from Sample1.disc.bam
[smoove] 2019/10/23 18:25:44 removed 1 singletons and isolated interchromosomals of 97 reads (1.03%) from Sample1.disc.bam in 0 seconds
[smoove] 2019/10/23 18:25:44 96 reads (97.96%) of the original 98 remain from Sample1.disc.bam
[smoove] 2019/10/23 18:25:44 removed 0 alignments out of 0 (NaN%) with low mapq, depth > 1000, or from excluded chroms from Sample1.split.bam in 0 seconds
[smoove] 2019/10/23 18:25:44 removed 0 alignments out of 0 (NaN%) that were bad interchromosomals or flanked-splitters from Sample1.split.bam
[smoove] 2019/10/23 18:25:44 removed 0 singletons of 0 reads (NaN%) from Sample1.split.bam in 0 seconds
[smoove] 2019/10/23 18:25:44 0 reads (NaN%) of the original 0 remain from Sample1.split.bam
[smoove] 2019/10/23 18:25:44 starting lumpy
[smoove] 2019/10/23 18:25:44 wrote lumpy command to /bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/SecondPanel/1_SVcalling/Lumpy/Results//Lumpy-lumpy-cmd.sh
[smoove] 2019/10/23 18:25:44 writing sorted, indexed file to /bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/SecondPanel/1_SVcalling/Lumpy/Results/Lumpy-smoove.genotyped.vcf.gz
[smoove] 2019/10/23 18:25:44 excluding variants with all unknown or homozygous reference genotypes
[smoove] 2019/10/23 18:25:45 chr6	1000000
chr6	2000000
chr6	4000000
chr6	8000000
chr6	16000000
chr6	32000000
chr6	64000000
chr6	128000000
chr6	256000000
[smoove] 2019/10/23 18:25:45 chr17	1000000
chr17	
[smoove] 2019/10/23 18:25:45 2000000
chr17	4000000
chr17	8000000
chr17	16000000
chr17	32000000
chr17	64000000
[smoove] 2019/10/23 18:25:45 > gsort version 0.0.6
[smoove] 2019/10/23 18:25:50 2019/10/23 18:25:50 EOF
[smoove] 2019/10/23 18:25:50 Failed to open -: unknown file type
[smoove] 2019/10/23 18:25:50 Failed to open -: unknown file type
panic: exit status 255

goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(...)
	/home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper(0xa88960, 0xc00000c118, 0x7ffd568659a0, 0x60, 0xc00016a670, 0x1, 0x1, 0x7ffd568658a4, 0x7c, 0x7ffd56865895, ...)
	/home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:226 +0x18c5
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:346 +0x468
main.main()

**Comment by brentp** [comment]
yes, the error should be better for this, but you are sending an empty file (no split reads). try on a larger test-case.
or PR accepted to give a better error message.

**Comment by TendoLiu** [comment]
Sorry do you mean there is no split reads (no SV events) in the bam file I input? And the package is working well? Not sure what is "PR accepted"...

**Comment by brentp** [comment]
yes, you sent in a tiny bam file with very few reads. this is causing an error somewhere because there's something that's expecting input, but not getting it.

I mean I'd be happy to accept a pull request that gives a better message and an empty result VCF for a case like this.

**Comment by TendoLiu** [comment]
In fact the bam is not extremely small. It is UMI collapsed bam file, about 400M.

**Comment by brentp** [comment]
there is very little signal for SV in the bam.

**Comment by TendoLiu** [comment]
OK. Thanks. Will try other bam files.
