### ISSUE TITLE
question about  ”run cnvnator in parallel”？

### ISSUE THREAD

**Issue by zyworship** [brentp/smoove#93]
Hi, dear brentp,
 I have run the "smoove call" with 8 samples. This is a small cohorts. I don't know the meaning about the  "cnvnator    : run cnvnator in parallel" and "hipstr      : run hipSTR in parallel"; Could I run "smoove cnvnator -f ... bam bam bam" instead of running the  CNVNator pipline?

And, I could run the "smoove cnvnator " directly ? Without another steps?

Thank you very much
Zhangyi

**Comment by brentp** [comment]
hi, smoove cnvnator is not supported. if you choose, you can run it per-sample, but i did not figure out how to get good results from cnvnator.
smoove hipstr is just a wrapper to run hipstr using as many threads as available.
