### ISSUE TITLE
pass smoove split and disc bams from samblaster

### ISSUE THREAD

**Issue by biobenkj** [brentp/smoove#98]
Hi Brent,

Thanks so much for smoove! Is it possible to directly pass smoove split and disc bams out of samblaster, similar to lumpyExpress?

Thanks!

Ben

**Comment by brentp** [comment]
smoove looks for $sample.split.bam and sample.disc.bam in the output directory. if they are there, then it will use them.

**Comment by biobenkj** [comment]
baller. thank you so much!
